
```{r}
# library(ruler)
library(tidyverse)
library(data.table)
library(latex2exp)
library(ggfortify)
library(compositions)
library(conflicted)
library(stringr)
library(glue)
library(ggrepel)
library(cowplot, help, pos = 2, lib.loc = NULL)
library(ggforce, help, pos = 2, lib.loc = NULL)
conflicted::conflict_prefer(name = "select", winner = "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("summarise", "dplyr")
detach("package:tidylog")
```

```{r}
source("load-data.R")
```
```{r}
IS_IGC=""
IS_IGC="-no-igc"

SD_var = "SDnoIGC"
SD_var = "SD"
SD_var = "SDIGC"

population = ""
population = "_population"

unique_targets <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/Unique_targets.txt"))

# for saving results 
wb <- createWorkbook()

for( SD_var in c("SD", "SDnoIGC", "SDIGC") ){
    for( population in c("") ) { #, "_population"
        sd_targets <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/{SD_var}_targets.txt"))
        targets <- bind_rows(
            list(SD = sd_targets, Unique = unique_targets),
            .id = "stratify"
        )
        colnames(targets)[2:3] <- c("first_three_bases", "target_count")
        spectra <- fread(glue("data/mutyper-results{IS_IGC}/tables/stratify/spectra_{SD_var}_Unique{population}.tbl")) %>%
            mutate(
                stratify = case_when(
                    stratify == SD_var ~ "SD",
                    TRUE ~ stratify 
                ),
                change_to = substr(spectra, 6,6),
                change = paste(first_base, ">", change_to)
            ) %>% 
            merge(targets, by = c("first_three_bases", "stratify")) %>%
            # normalize counts so same # of counts happen in SD and unique 
            group_by(stratify) %>%
            mutate(
                #norm = sum(count)/sum(target_count),
                #count = count / sum(count),
                #target_count = target_count / sum(target_count)
            ) %>%
            ungroup() %>%
            mutate(
                #target_percent = count / target_count * 100,
                #count_adj = count / target_count,
            ) %>%
            as.data.table()
        spectra
        print( spectra %>% group_by(stratify) %>% summarise(sum(count)/1e6,sum(target_count)/1e6) )
        table(spectra$stratify)

        grouped_spectra <- spectra %>%
            group_by(
                stratify, mid_base,
                spectra, first_base, last_base,
                first_three_bases, first_two_bases,
                change, change_to,
                target_count
            ) %>%
            summarise(count = sum(count), n_samples = length(unique(sample))) %>%
            mutate(
                count_adj = count / target_count,
                target_percent = count / target_count,
                spectra = gsub(">.", ">", spectra),
                spectra = gsub(".$", "", spectra),
            ) %>%
            group_by(stratify) %>%
            mutate(target_percent = target_percent / sum(target_percent)) %>%
            as.data.table()
        grouped_spectra

        k=grouped_spectra %>%
            group_by(stratify) %>%
            summarise(sum(count), sum(target_count), sum(target_percent))
        print(k)

        spectra_table <- grouped_spectra %>%
            mutate(
                #y = count_adj,
                y = target_percent,
            ) %>%
            pivot_wider(
                names_from = c("stratify"), values_from = "y",
                id_cols = c("spectra", "first_base", "mid_base", "first_three_bases", "change", "change_to"),
            ) %>%
            mutate(
                y = log2(SD / Unique),
                # y= SD/Unique,
                size = abs(SD - Unique),
                z_rank = rank(y),
                per = z_rank / max(z_rank),
                `# GC bases` = as.character(str_count(first_three_bases, "G|C"))
            ) %>%
            arrange(
                `# GC bases`,
                y,
                mid_base,
                spectra,
            ) %>%
            mutate(
                spectra = factor(spectra, levels = spectra)
            ) %>%
            as.data.table()
        spectra_table

        spectra_plot <- spectra_table %>%
            data.table() %>%
            ggplot(
                aes(
                    x = spectra,
                    y = y, label = spectra,
                    color = `# GC bases`,
                    # size=size,
                    # size = 3,
                )
            ) + # , color = stratify)) +
            geom_point(size = 3) +
            scale_x_discrete(guide = guide_axis(n.dodge = 6)) +
            geom_text_repel(
                data = . %>% filter(per <= 0.10 | per >= 0.90),
                nudge_y = .05, # )/10,
                nudge_x = -1,
                force = 20,
                # direction = "y",
                color = "black",
                size = 3,
            ) +
            theme_minimal_grid() +
            facet_row(~change, scales = "free_x")+
            scale_color_viridis_d(direction = -1) +
            # triplet-normalized mutation frequency
            ylab(TeX("$ log_2 \\; \\frac{SD \\; triplet-normalized \\; mutation \\; frequency}{Unique \\; triplet-normalized \\; mutation \\; frequency}$")) +
            xlab("Mutation event") +
            theme(
                legend.position = "top",
                plot.margin = margin(0.1, 1, 0.1, 0.1, unit = "cm"),
            ) +
            coord_cartesian(clip = "off")
        spectra_plot
        #ggsave(glue("figures/seq_comp{IS_IGC}.pdf"), width = 12)
        #ggsave("tmp.pdf", width = 12)



        #sum(fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/{SD_var}_spectra.txt"))[, 2:97]) / 1e6
        #sum(fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/Unique_spectra.txt"))[, 2:97]) / 1e6

        
        ########################################################################################
        ########################################################################################
        ########################################################################################

        target_diffs <- targets %>%
            pivot_wider(
                names_from = c("stratify"), values_from = "target_count",
                id_cols = c("first_three_bases"),
            ) %>%
            mutate(
                total_sd = sum(SD),
                total_u = sum(Unique),
                fold = (SD / total_sd) / (Unique / total_u),
                log2 = log2(fold)
            ) %>%
            rowwise() %>%
            mutate(
                matrix = list(
                    matrix(c(SD, Unique, total_sd - SD, total_u - Unique), nrow = 2)
                ),
                # stat_test = list(chisq.test(c(SD, Unique), c(total_sd, total_u))),
                # stat_test = fisher.test(matrix)$p.value,
                stat_test = list(chisq.test(matrix)), # $p.value,
                pval = stat_test$p.value * nrow(.),
                `# GC bases` = as.character(str_count(first_three_bases, "G|C"))
            ) %>%
            ungroup() %>%
            arrange(
                `# GC bases`,
                log2,
                first_three_bases
            ) %>%
            mutate(
                first_three_bases = factor(first_three_bases, levels = first_three_bases)
            )
        target_diffs

        target_plot <- ggplot(
            target_diffs,
            aes(
                x = first_three_bases,
                y = log2,
                # y = -log10(pval),
                # color = pval < 0.05,
                label = first_three_bases,
                color = `# GC bases`,
            )
        ) +
            geom_point(size = 3) +
            scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
            scale_color_viridis_d(direction = -1) +
            ylab(TeX("$ log_2 \\; \\frac{SD \\; composition}{Unique \\; composition}$")) +
            xlab("") +
            theme_minimal_grid() +
            theme(legend.position = "top")

        ########################################################################################
        ########################################################################################
        ########################################################################################



        spectra_wide <- spectra %>%
            mutate(target_percent = count/target_count) %>%
            group_by(stratify) %>%
            mutate(target_percent = target_percent / sum(target_percent)) %>%
            ungroup() %>%
            merge(pop_small, by.x = "sample", by.y = "SampleID", all.x=TRUE) %>%
            # filter(stratify == "Unique") %>%
            pivot_wider(id_cols = c("stratify", "sample", "Superpopulation"), names_from = c("spectra"), values_from = c("target_percent")) %>%
            data.table()
        spec_mat <- spectra_wide[, 4:ncol(spectra_wide)]
        spec_mat %>% as.tibble()
        # normatize per row
        spec_mat <- t(apply(spec_mat, 1, function(x) (x) / (sum(x))))
        # log scale per will suggestion
        spec_mat <- clr(spec_mat)

        spectra_pca <- prcomp(spec_mat, scale. = TRUE)
        sort(spectra_pca$rotation[, 1])

        pca_plot <- spectra %>%
            merge(pop_small, by.x = "sample", by.y = "SampleID", all.x=TRUE) %>%
            ggplot(
                aes(
                    x = PC1,
                    y = PC2,
                    color = Superpopulation,
                    # shape = stratify,
                )
            ) +
            geom_point() +
            theme_minimal_grid() +
            facet_row(~stratify, scales = "free") +
            theme(legend.position = "top")

        pca_plot <- autoplot(spectra_pca,
            data = spectra_wide,
            colour = "Superpopulation",
            shape = "stratify",
            # x = 4, y = 5
        ) +
            scale_color_brewer("", palette = "Set1") +
            scale_shape_discrete("") +
            guides(
                color = guide_legend(nrow = 2),
                shape = guide_legend(nrow = 2)
            ) +
            theme_minimal_grid() +
            theme(
                legend.position = "top"
            )

        #ggsave("tmp.pdf")

        ########################################################################################
        ########################################################################################
        ########################################################################################

        grep_term="(A|T).>(C|G)"
        get_enrichment <- function(spectra_table, grep_term){
            z= spectra_table %>%
            arrange(-y) %>% 
            mutate(`Fold change`=2**y, z = SD/Unique  ) %>%
            select(spectra,`Fold change`, SD, Unique) %>%
            filter(grepl(grep_term, spectra)) %>%
            summarise(
                change=sum(SD)/sum(Unique),
            )
            round(z[[1]],3)
        }

        #anno = data.frame(  spectra=c("GCG>G","TCG>T"),
        #    y=c(get_enrichment(spectra_table,"C.>G"), get_enrichment(spectra_table,"CG>T"))
        #)
        library(ggplot2)
        my_x = 3
        spectra_plot_anno=spectra_plot + ggplot2::annotate("text",
            x = my_x, 
            y = 0.25,
            label = glue('.CG > T {get_enrichment(spectra_table,"CG>T")}')
        ) + ggplot2::annotate("text",
            x = my_x, 
            y = 0.35,
            label = glue('C > G {get_enrichment(spectra_table,"C.>G")}')
        ) + ggplot2::annotate("text",
            x = my_x, 
            y = 0.45,
            label = glue('(C,G) > (A,T) {get_enrichment(spectra_table,"(C|G).>(A|T)")}')
        ) + ggplot2::annotate("text",
            x = my_x, 
            y = 0.55,
            label = glue('(A,T) > (C,G) {get_enrichment(spectra_table,"(A|T).>(C|G)")}')
        )

        layout <- "
        AAAABBBBBB
        AAAACCCCCC
        DDDDDDDDDD
        DDDDDDDDDD
        "
        library(patchwork)
        fig <- plot.timing + target_plot + pca_plot + spectra_plot_anno + # plot.timing +
            plot_layout(design = layout) +
            plot_annotation(tag_levels = "a") & theme(plot.tag = element_text(size = 24))
        scale <- 0.8
        #ggsave("tmp.pdf", fig, width = 16 * scale, height = 16 * scale)
        ggsave(glue("figures/full-figs/mutyper{population}_{SD_var}.pdf"), fig, width = 16 * scale, height = 16 * scale)
    }

    # save data
    sheet = spectra_table %>%
        arrange(-y) %>% 
        mutate(`Fold change`=2**y) %>%
        select(spectra,`Fold change`, SD, Unique) 
    addWorksheet(wb = wb, sheetName = SD_var, gridLines = FALSE)
    writeData(wb = wb, sheet = SD_var, x = sheet)
}

saveWorkbook(wb, "tables/Triplet_fold_increases.xlsx",  overwrite = TRUE)


```



# some stats from the figs
```{r}

spectra_table <- data.table(spectra_table)
spectra_table[grepl(".CG>T", spectra), ] %>%
    mutate(ave = 1 - SD / Unique) %>%
    summarise(mean(ave), 1-mean(2**y), 1-sum(SD)/sum(Unique))

targets %>%
    mutate(mid_base = substr(first_three_bases, 2, 2)) %>%
    group_by(stratify) %>%
    mutate(total = sum(target_count)) %>%
    group_by(mid_base, stratify) %>%
    summarise(
        frac = sum(target_count) / total,
        total
    ) %>%
    unique()
t.test( 
    x=c(rep(1,122193647*0.424), rep(0,122193647*(1-.424))  ),
    #y=c(rep(1, 2542623043/1e4*.408), rep(0, 2542623043/1e4*(1-.408) )  ),
    mu = 0.408,
    alternative = "greater"
)
```



```{r}


get_enrichment <- function(spectra_table, grep_term){
    spectra_table %>%
    arrange(-y) %>% 
    mutate(`Fold change`=2**y, z = SD/Unique  ) %>%
    select(spectra,`Fold change`, SD, Unique) %>%
    filter(grepl(grep_term, spectra)) %>%
    summarise(
        change=sum(SD)/sum(Unique),
    )
}
get_enrichment(spectra_table,"C.>G")
get_enrichment(spectra_table,"C.>T")
```


```{r}

t.p = grouped_spectra %>%
    group_by(stratify) %>%
    mutate(norm_target_percent = target_percent/sum(target_percent) * 100) %>%
    ungroup() %>%
    pivot_wider(id_cols=c("spectra", "first_three_bases"),names_from=stratify, values_from=norm_target_percent) %>%
    mutate(`# GC bases` = as.character(str_count(first_three_bases, "G|C"))) %>%
    arrange(-Unique) %>%
    mutate(spectra = factor(spectra, levels=unique(spectra)))

ggsave("tmp.pdf")


t.p.p=t.p %>%
    ggplot(aes(color=`# GC bases`, y = Unique, x=spectra) ) +
    geom_point() + 
    facet_col(~`# GC bases`)


ggsave("tmp.pdf")
```


# unused chunks ?
```{r }
seq_con.df <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/seq_content.tbl"))
colnames(seq_con.df)[length(seq_con.df)] <- "stratify"

seq_summary <- seq_con.df %>%
    filter(stratify %in% c("SD", "Unique")) %>%
    group_by(stratify) %>%
    summarise(
        A = sum(`6_num_A`),
        C = sum(`7_num_C`),
        G = sum(`8_num_G`),
        T = sum(`9_num_T`)
    ) %>%
    group_by(stratify) %>%
    mutate(
        Total = (sum(A) / 1e3 + sum(T) / 1e3 + sum(G) / 1e3 + sum(C) / 1e3) * 1e3,
        GC = (sum(G) + sum(C)) / Total,
        AT = (sum(A) + sum(T)) / Total
    )

z <- spectra %>%
    group_by(
        stratify, mid_base,
        spectra, first_base, last_base,
        first_three_bases, first_two_bases,
        target_count
    ) %>%
    summarise(count = sum(count)) %>%
    merge(seq_summary)

```