```{r load-data, include=FALSE}
source("load-data.R")
source("utils/gene-conversion-utils.R")
```

### ECDF IGC code

```{r ECDF}
df.ecdf <- df.all %>%
    dplyr::select(sample, cum.bp, name, Superpopulation) %>%
    mutate(cum.bp = as.numeric(cum.bp)) %>%
    mutate(name = as.numeric(name)) %>%
    group_by(name, sample, Superpopulation) %>%
    summarise(cum.bp = c(max(cum.bp), min(cum.bp)) / 1e6) %>%
    data.table()

df.sum.ecdf <- df.all %>%
    arrange(-name) %>%
    group_by(Superpopulation) %>%
    mutate(cum.bp = cumsum(length) / length(unique(sample))) %>%
    dplyr::select(cum.bp, name, Superpopulation) %>%
    group_by(name, Superpopulation) %>%
    summarise(cum.bp = c(max(cum.bp), min(cum.bp)) / 1e6) %>%
    data.table()

df.text.ecdf <- df.ecdf %>%
    mutate(log = log10(name), g = ceiling(log)) %>%
    group_by(g, sample, Superpopulation) %>%
    summarise(cum.bp = max(cum.bp), name = name[which.max(cum.bp)]) %>%
    group_by(g, Superpopulation) %>%
    summarise(name = mean(name), sd = sd(cum.bp), cum.bp = mean(cum.bp)) %>%
    mutate(label = paste(round(cum.bp, 2), "+/-", round(sd, 2))) %>%
    drop_na()
# %>%  mutate(Superpopulation="Total")
df.text.ecdf

p.mbp.gc <- ggplot(
    df.ecdf,
    aes(x = name, y = cum.bp, group = paste0(sample, Superpopulation))
) +
    geom_line(
        alpha = 0.99, size = 0.2,
        linetype = "dashed", aes(color = Superpopulation)
    ) + # (geom = "step")+
    geom_line(
        data = df.sum.ecdf,
        aes(group = Superpopulation), color = "black", size = 1.5, alpha = 0.6
    ) + # (geom = "step")+
    geom_text_repel(
        data = df.text.ecdf, aes(label = label, group = "a"),
        nudge_x = 0.5, nudge_y = 4,
        arrow = arrow(length = unit(0.1, "cm")), color = "black"
    ) +
    scale_x_continuous(trans = "log10", label = comma) +
    scale_y_continuous(labels = comma) +
    annotation_logticks(side = "b") +
    scale_color_brewer(palette = "Set1") +
    xlab("Number of SNV events that must map better at a new location") +
    ylab("Average Mbp of gene conversion per haplotype") +
    facet_wrap(~Superpopulation, ncol = 2) +
    theme_minimal_grid() +
    theme(legend.position = "none")
my_ggsave("{odir}/igc.mbp.pdf", width = 12 * 0.75, height = 16 * 0.75, plot = p.mbp.gc)


p.mbp.gc <- ggplot(
    df.ecdf %>% filter(Superpopulation == "Total"),
    aes(x = name, y = cum.bp, group = sample)
) +
    geom_line(alpha = 0.99, size = 0.2, linetype = "dashed") +
    geom_line(
        aes(group = Superpopulation),
        data = df.sum.ecdf %>% filter(Superpopulation == "Total"),
        color = "black", size = 1.5, alpha = 0.6
    ) +
    geom_text_repel(
        data = df.text.ecdf %>% filter(Superpopulation == "Total"),
        aes(label = label, group = "a"),
        nudge_x = 0.5, nudge_y = 4,
        arrow = arrow(length = unit(0.1, "cm")), color = "black"
    ) +
    scale_x_continuous(trans = "log10", label = comma) +
    scale_y_continuous(labels = comma) +
    annotation_logticks(side = "b") +
    xlab("Number of SNV events that must map better at a new location") +
    ylab("Average Mbp of gene conversion per haplotype") +
    # facet_wrap(~Superpopulation, ncol = 2) +
    theme_minimal_grid() +
    theme(legend.position = "none")
my_ggsave("{odir}/igc.mbp.simple.pdf", width = 8, height = 6, plot = p.mbp.gc)
```

ECDF for CHM1 only

```{r}
p.mbp.gc <- ggplot(
    df.ecdf %>% filter(sample == "CHM1_1"),
    aes(x = name, y = cum.bp, group = paste0(sample, Superpopulation))
) +
    geom_line(alpha = 0.99, aes(color = Superpopulation)) + # (geom = "step")+
    # geom_text_repel(
    #    data = df.text.ecdf, aes(label = label, group = "a"),
    #    nudge_x = 0.5, nudge_y = 4, arrow = arrow(length = unit(0.1, "cm")), color = "black"
    # ) +
    scale_x_continuous(trans = "log10", label = comma) +
    scale_y_continuous(labels = comma) +
    annotation_logticks(side = "b") +
    scale_color_brewer(palette = "Set1") +
    xlab("Number of SNV events that must map better at a new location") +
    ylab("Average Mbp of gene conversion per haplotype") +
    theme_minimal_grid() +
    theme(legend.position = "none")
my_ggsave("{odir}/CHM1_divergence_ecdf.pdf", width = 8, height = 8, plot = p.mbp.gc)
```

## Length and support

```{r Length and support}
library(gt)
library(ggtext)
len_sum <- quantile(pre_merged_df$length / 1e3, c(0.25, 0.5, 0.75, 0.9, 0.95, .99, 1))
len_sum <- c(len_sum, mean = mean(pre_merged_df$length / 1000))
len_sum
html_sum <- t(len_sum) %>%
    as_tibble() %>%
    gt() %>%
    as_raw_html(inline_css = TRUE)
len_text <- res_scalar <- paste0(capture.output(
    print(round(len_sum, 2))
), collapse = "\n")
len_text

pre_merged_df <- pre_merged_df %>%
    mutate(length = reference_end - reference_start)
p.len <- pre_merged_df %>%
    ggplot(aes(x = length)) +
    geom_histogram(bins = 70) +
    scale_x_continuous(label = comma, trans = "log10") +
    # scale_x_continuous(label = comma) +
    scale_y_continuous(labels = comma) + # , trans = "log10") +
    annotation_logticks(side = "b") +
    ylab("Count") +
    xlab("Length of IGC") +
    # ggtitle("", subtitle = len_text) +
    theme_minimal_grid() +
    theme(legend.position = "none")
my_ggsave("{odir}/igc_len.pdf", width = 8, height = 4, plot = p.len)

snv_sum <- quantile(pre_merged_df$name, c(0.25, 0.5, 0.75, 0.9, 0.95, .99, 1))
snv_sum <- c(snv_sum, mean = mean(pre_merged_df$name))
snv_sum
mean(pre_merged_df$name / pre_merged_df$length * 1000)

p.snv <- igc %>%
    ggplot(aes(x = name)) +
    geom_histogram(bins = 50) +
    scale_x_continuous(label = comma, trans = "log10") +
    scale_y_continuous(labels = comma, trans = "log10") +
    annotation_logticks(side = "b") +
    ylab("") +
    xlab("") +
    theme_minimal_grid() +
    theme(legend.position = "none")
my_ggsave("{odir}/snv.pdf", width = 8, height = 2, plot = p.snv)


my_lab <- function(x) {
    comma(10**x)
}

p.len.snv <- igc %>%
    # filter(name > 0 & length > 500) %>%
    ggplot(aes(x = length, y = name)) +
    geom_hex(aes(fill = stat(log10(count))), bins = 20) +
    stat_cor(method = "pearson") +
    # geom_point(alpha=0)+
    geom_smooth(method = "lm", se = FALSE, size = 1.5, color = "darkred", linetype = "dashed") +
    scale_x_continuous(label = comma, trans = "log10") +
    scale_y_continuous(labels = comma, trans = "log10", lim = c(0.9, NA)) +
    scale_fill_viridis_c("IGC count", option = "magma", labels = my_lab) +
    xlab("IGC length (bp)") +
    ylab("# of IGC supporting SNVs") +
    annotation_logticks() +
    theme_minimal_grid() +
    theme(legend.position = "right")
# ggMarginal(p.len.snv, type="histogram")
my_ggsave("{odir}/len.snv.pdf", width = 8, height = 6, plot = p.len.snv)
```

##

```{r, ideogram figure }
min_n <- 10
min_sample <- 2
myn <- 1e9
merged_df

igc_sd <- igc_sd %>%
    group_by(group) %>%
    mutate(igc_count = n()) %>%
    ungroup() %>%
    data.table()

kp.df <- igc_sd[
    reference_name == `#reference_name.liftover` & name >= min_n & igc_count >= min_sample
] %>%
    head(myn) %>%
    data.table()
colnames(igc_sd)
dim(kp.df)

pdf(glue("{odir}/intra-gc-with-freq-at-least-{min_n}-{min_sample}.pdf"),
    height = 7, width = 14
)
kp <- plotKaryotype(
    genome = converter$genome, cytobands = converter$cyto, chromosomes = NOYM,
    plot.type = 2
)
kpPlotLinks(kp,
    data = toGRanges(
        kp.df[
            reference_start < reference_start.liftover,
            c("#reference_name.liftover", "reference_start.liftover", "reference_end.liftover")
        ]
    ),
    data2 = toGRanges(
        kp.df[
            reference_start < reference_start.liftover,
            c("reference_name", "reference_start", "reference_end")
        ]
    ),
    col = transparent("#003950", amount = 0),
    border = NA
    # border = transparent(OLDCOLOR, amount = 0.9)
)

kpPlotLinks(kp,
    data = toGRanges(
        kp.df[
            reference_start > reference_start.liftover,
            c("#reference_name.liftover", "reference_start.liftover", "reference_end.liftover")
        ]
    ),
    data2 = toGRanges(
        kp.df[
            reference_start > reference_start.liftover,
            c("reference_name", "reference_start", "reference_end")
        ]
    ),
    col = transparent("darkorange", amount = 0),
    border = NA,
    data.panel = 2
    # border = transparent(OLDCOLOR, amount = 0.9)
)

dev.off()
```

```{r}
###
cir.df <- merged_df[
    reference_name != `#reference_name.liftover` & n >= min_n
] %>%
    filter(reference_name != "chrY" & `#reference_name.liftover` != "chrY") %>%
    head(myn) %>%
    data.table()

cyto.df <- data.frame(CYTOFULL)[
    ,
    c("seqnames", "start", "end", "seqnames", "gieStain")
] %>% filter(seqnames != "chrY")
cyto.df <- cyto.df[order(cyto.df$gieStain, cyto.df$seqnames), ]
cyto.df$seqnames <- as.character(cyto.df$seqnames)
# ploting
pdf(glue("{odir}/inter-gc-with-freq-at-least-{min_n}.pdf"), height = 6, width = 6)
circos.clear()
circos.par(cell.padding = c(0, 0, 0, 0))
circos.initializeWithIdeogram(cyto.df, ideogram.height = .05, sort.chr = T)
# circos.genomicRect(enriched[,1:3], ybottom =0, ytop=1, border = NA, col="red")
# circos.genomicRainfall(sedef[,1:3])
# circos.genomicRainfall(sedef.inter[,1:3]);  circos.genomicRainfall(sedef.inter[,c("chr2","start2", "end2")])
d1 <- cir.df[
    ,
    c("#reference_name.liftover", "reference_start.liftover", "reference_end.liftover")
]
d2 <- cir.df[
    ,
    c("reference_name", "reference_start", "reference_end")
]
circos.genomicLink(d1, d2, col = NEWCOLOR, border = transparent(NEWCOLOR, amount = 0.95))
dev.off()
```

## Donor vs acceptor across the genome

```{r}
igc_a.sd <- igc_sd[, c(acceptor_columns, "sample"), with = FALSE]
igc_d.sd <- igc_sd[, c(donor_columns, "sample"), with = FALSE]

pp <- getDefaultPlotParams(plot.type = 3) # $plot.params
pp$ideogramlateralmargin <- 0.01
# pp$ideogramheight=100
pdf(glue("{odir}/ideo_gc_density.pdf"), height = 4, width = 18)
kp <- plotKaryotype(
    cytobands = converter$cyto,
    genome = converter$genome,
    plot.params = pp, plot.type = 3,
)

window <- 2e5
kpPlotDensity(kp,
    data = toGRanges(igc_a.sd),
    data.panel = 1, window.size = window, col = acceptor_color
) # , border=acceptor_color)
kpPlotDensity(kp,
    data = toGRanges(igc_d.sd),
    data.panel = 2, window.size = window, col = donor_color
) # , border=donor_color)

kpPlotRegions(kp,
    data = toGRanges(GENES_V1.1.sd),
    r0 = -pp$data1inmargin / pp$data1height,
    r1 = 0, avoid.overlapping = FALSE,
    data.panel = 2,
    border = NA
)

kpPlotRegions(kp,
    data = (toGRanges(morb_sd)), #-width(toGRanges(morb_sd))/25,
    r1 = 0, r0 = -pp$data2inmargin / pp$data2height,
    data.panel = 1,
    col = transparent(morb_sd$color, 0.0), avoid.overlapping = TRUE, border = NA
)


kpAddCytobandLabels(kp, cex = .75)
# kpPlotMarkers(kp, data=toGRanges(converter$cyto), labels=converter$cyto$name, text.orientation = "horizontal",
#              r1=0.5, cex=0.8,adjust.label.position = FALSE)

dev.off()
```

```{r distance between IGC}
acro <- c("chr13", "chr14", "chr15", "chr21", "chr22")
igc.dist <- pre_merged_df %>%
    filter(reference_name == `#reference_name.liftover`) %>%
    mutate(
        dist_between = pmin(
            abs(reference_start - reference_start.liftover),
            abs(reference_end - reference_end.liftover),
            abs(reference_end - reference_start.liftover),
            abs(reference_start - reference_end.liftover)
        ),
        reference_name = factor(reference_name, NOM)
    ) %>%
    mutate(ACRO = `reference_name` %in% acro | `#reference_name.liftover` %in% acro) %>%
    mutate(length = reference_end - reference_start) %>%
    data.table()

p.igc.dist <- igc.dist %>%
    ggplot(aes(x = dist_between, fill = reference_name)) +
    geom_histogram(bins = 30) + # binwidth = 10000) +
    scale_x_continuous(label = comma, trans = "log10") +
    annotation_logticks(side = "b") +
    theme_cowplot() +
    facet_col(~ACRO) +
    # facet_zoom(xlim = c(0, 1e6), zoom.size = 4) +
    xlab("Distance between IGC acceptor and donor site") +
    # scale_fill_manual("") +
    ylab("# of intrachromosomal IGC events") +
    guides(
        fill = guide_legend("", ncol = 8)
    ) +
    theme(
        legend.position = "bottom"
    )
my_ggsave("figures/igc_dist.pdf", height = 8, width = 8, plot = p.igc.dist)

thresh <- 10
p.igc.dist.len <- igc.dist %>%
    # filter(igc.dist$n > 1) %>%
    # filter(name > 10) %>%
    # filter(length > 1e3) %>%
    mutate(sSNV = case_when(
        name >= thresh ~ glue("{thresh} or more supporting SNVs"),
        TRUE ~ glue("less than {thresh} supporting SNVs")
    )) %>%
    ggplot(aes(x = dist_between, y = length)) +
    geom_hex(aes(fill = stat(log10(count))), bins = 20) +
    stat_cor(method = "pearson") +
    geom_smooth(method = "lm", se = F, alpha = 0.2, size = 1) +
    scale_x_continuous(label = comma, trans = "log10") +
    scale_y_continuous(label = comma, trans = "log10") +
    annotation_logticks(side = "lb") +
    scale_fill_viridis_c("IGC count", option = "magma", labels = my_lab) +
    theme_minimal_grid() +
    facet_col(~sSNV) +
    xlab("Distance between IGC acceptor and donor site") +
    ylab("Length of IGC event") +
    theme(
        # legend.position = "bottom"
    )

tmp <- igc.dist %>%
    # filter(igc.dist$n > 1) %>%
    # filter(name > 10) %>%
    # filter(length > 1e3) %>%
    mutate(sSNV = case_when(
        name >= thresh ~ glue("{thresh} or more supporting SNVs"),
        TRUE ~ glue("less than {thresh} supporting SNVs")
    )) %>%
    ggplot(aes(x = as.numeric(name))) +
    geom_histogram(bins = 100) +
    scale_x_continuous(label = comma, trans = "log10") +
    scale_y_continuous(label = comma, trans = "log10") +
    # annotation_logticks("") +
    theme_minimal_grid() +
    xlab("support")
my_ggsave("figures/igc_dist.pdf", height = 8, width = 8, plot = p.igc.dist.len)
```

```{r ideogram per haplotype}
# uses these from other block
min_snv <- 10
min_sample <- 2
condition <- TRUE

igc_sd <- igc_sd %>%
    group_by(group) %>%
    mutate(igc_count = n()) %>%
    ungroup() %>%
    data.table()

igc_sd$label <- paste(igc_sd$Superpopulation, igc_sd$Sample)
condition <- igc_sd$`#reference_name.liftover` == igc_sd$reference_name &
    igc_sd$name >= min_snv &
    igc_sd$igc_count >= min_sample &
    igc_sd$sample %in% unique(igc_sd$sample)[1:1000] &
    !(igc_sd$sample %in% c("GRCh38_2", "CHM1_2"))

a <- igc_sd[condition, c(acceptor_columns, "label"), with = FALSE]
d <- igc_sd[condition, c(donor_columns, "label"), with = FALSE]
acceptor_left <- a$reference_start.liftover < d$reference_start
dim(a)
dim(d)
sum(a$reference_start.liftover > a$reference_end.liftover)
sum(d$reference_start > d$reference_end)
mean(morb_sd$end - morb_sd$start) / 1e6
mean(morb$end - morb$start) / 1e6

chrs <- c("chr1", "chr2", "chr15", "chr16")
make_gc_ideogram(a, d, chrs, "figures/subset_all_border_gc_events.pdf", height = 36 / 2, width = 55 / 2)
make_gc_ideogram(a, d, NOYM, glue("figures/all_border_gc_events_{min_snv}_{min_sample}.pdf"))

for (chrm in NOM) {
    make_gc_ideogram(a, d, chrm,
        glue("figures/chrs/{chrm}_border_gc_events.pdf"),
        height = 42 / 2, width = 32 / 2
    )
}

chrm <- "chr15"
make_gc_ideogram(a, d, chrm,
    glue("figures/chrs/{chrm}_border_gc_events.pdf"),
    height = 36, width = 12
)
```

# TABLES

```{r}
# library(dtplyr)
# detach("package:dtplyr")
# library(dplyr, warn.conflicts = FALSE)
library(conflicted)
conflicted::conflict_prefer(name = "rename", winner = "dplyr")
conflict_prefer("rename", "dplyr")

out_igc <- IGC %>%
    # head(1000) %>%
    add_gene_list_col(
        genelist = ALL_GENES_V1.1,
        cols = acceptor_columns,
        outcol = "orthologous.genes"
    ) %>%
    add_gene_list_col(
        genelist = ALL_GENES_V1.1,
        outcol = "IGC.genes", cols = donor_columns
    ) %>%
    select(-thickStart, -thickEnd, -color, -strand, -score, -status, -cum.bp, -igc_count, -Sex, -Population) %>%
    dplyr::rename(setNames(names(.), gsub("\\.liftover", ".acceptor", names(.)))) %>%
    dplyr::rename(setNames(names(.), gsub(".*reference_name", "chrm", names(.)))) %>%
    dplyr::rename(setNames(names(.), gsub("reference_", "", names(.)))) %>%
    dplyr::rename_with(function(.) {
        "# of supporting SNVs"
    }, name) %>%
    mutate(kbp = comma((end - start) / 1e3, accuracy = 0.1)) %>%
    rename_with(function(c) {
        paste0(c, ".donor")
    }, matches("^(chrm|start|end|mismatches|perID_by_all)$")) %>%
    group_by(group) %>%
    mutate(`Seen in n samples` = length(unique(sample))) %>%
    separate(sample, c("SampleID", "hap"), sep = "_") %>%
    # merge(pop_small, all.x = T, by = "SampleID") %>%
    dplyr::select(-Sample) %>%
    data.table()

out_igc %>%
    openxlsx::write.xlsx("tables/Master_IGC.xlsx",
        colWidths = 10,
        firstRow = TRUE,
        firstCol = TRUE,
        gridLines = FALSE, colNames = TRUE
    )

out_igc %>% head(3)
dim(out_igc)
colnames(merged_df)
colnames(out_igc)
out_merged_df <- merged_df %>%
    dplyr::rename(setNames(names(.), gsub("\\.liftover", ".acceptor", names(.)))) %>%
    dplyr::rename("# of supporting SNVs" = name) %>%
    dplyr::rename("Seen in n haplotypes" = n) %>%
    as.data.table() %>%
    dplyr::rename(setNames(names(.), gsub(".*reference_name", "chrm", names(.)))) %>%
    as.data.table() %>%
    rename_with(function(c) {
        paste0(c, ".donor")
    }, matches("^(chrm|start|end|mismatches|perID_by_all)$")) %>%
    select(-thickStart, -thickEnd, -igc_count, -`cum.bp`) %>%
    as.data.table()

out_merged_df %>%
    openxlsx::write.xlsx("tables/Master_merged_IGC.xlsx",
        colWidths = 10,
        firstRow = TRUE,
        firstCol = TRUE,
        gridLines = FALSE, colNames = TRUE
    )
dim(out_merged_df)
```

```{r}
out_igc$Haplotype <- "All"
out_merged_df$Haplotype <- "All"
hap_out_igc <- copy(out_igc)
hap_out_igc$Haplotype <- paste(hap_out_igc$SampleID, hap_out_igc$hap)
sum_df <- bind_rows(
    list(
        `All events` = out_igc,
        `All events (min 5 SNVs)` = out_igc[`# of supporting SNVs` >= 5],
        `All events (min 10 SNVs)` = out_igc[`# of supporting SNVs` >= 10],
        `Merged events` = out_merged_df,
        `Merged events (min 5 SNVs)` = out_merged_df[`# of supporting SNVs` >= 5],
        `Merged events (min 10 SNVs)` = out_merged_df[`# of supporting SNVs` >= 10],
        `By sample` = hap_out_igc,
        `By sample (min 5 SNVs)` = hap_out_igc[`# of supporting SNVs` >= 5],
        `By sample (min 10 SNVs)` = hap_out_igc[`# of supporting SNVs` >= 10]
    ),
    .id = "Category"
) %>%
    mutate(
        Superpopulation = case_when(!startsWith(Category, "By sample") ~ "NA", TRUE ~ as.character(Superpopulation)),
        Category = factor(Category, levels = unique(Category)),
    ) %>%
    group_by(Category, Haplotype, Superpopulation) %>%
    summarise(
        `Ave. # of supporting SNVs` = mean(`# of supporting SNVs`),
        `Ave. # of supporting SNVs per kbp` = mean(`# of supporting SNVs` / length * 1000),
        `Ave. length` = mean(`length`),
        `Max IGC length` = max(`length`),
        count = n()
    ) %>%
    arrange(Category, Superpopulation, Haplotype) %>%
    as.data.table()
sum_df
sum_df %>%
    openxlsx::write.xlsx("tables/Summary_IGC_stats.xlsx",
        colWidths = 25,
        firstRow = TRUE,
        firstCol = TRUE,
        gridLines = FALSE, colNames = TRUE
    )
```

## Make a gene intersection table

```{r}
###
igc_in_genes <- function(gene_bed, gene_based = TRUE, df = IGC) {
    gene_cols <- c(
        "gene", "gene_length",
        "gene_chr", "gene_start",
        "gene_end", "gene_name"
    )
    gene_cols <- unique(c(gene_cols, pli_cols))
    gene_cols
    grouped_genes <- gene_bed %>%
        filter(geneType == "protein_coding") %>%
        group_by(chr, gene, strand) %>%
        mutate(gene_length = end - start) %>%
        dplyr::slice(which.max(gene_length)) %>%
        mutate(
            gene_chr = chr,
            gene_start = start,
            gene_end = end
        ) %>%
        data.table()
    grouped_genes
    df$IGC_ID <- paste(df$sample, paste0("ID:", 1:nrow(df)), sep = "_")
    head(df$ID)
    o <- findOverlaps(
        toGRanges(grouped_genes[, c("chr", "start", "end")]),
        toGRanges(df[, ..acceptor_columns])
    )
    o2 <- findOverlaps(
        toGRanges(grouped_genes[, c("chr", "start", "end")]),
        toGRanges(df[, ..donor_columns])
    )
    gene_acceptor <- cbind(
        grouped_genes[
            queryHits(o),
            ..gene_cols
        ],
        df[subjectHits(o)]
    )
    gene_donor <- cbind(
        grouped_genes[
            queryHits(o2),
            ..gene_cols
        ],
        df[subjectHits(o2)]
    )
    gene_donor$status <- "Donor"
    gene_igc <- rbind(gene_acceptor, gene_donor)

    if (FALSE) {
        no_hits <- grouped_genes[!unique(c(queryHits(o), queryHits(o2))), ..gene_cols]
        length(unique(no_hits$gene_id)) + length(unique(gene_igc$gene_id))
        length(unique(grouped_genes$gene_id))
        no_hits$status <- "NoIGC"
        gene_igc <- rbind(gene_igc, no_hits, fill = TRUE)
    }

    if (gene_based) {
        out_df <- gene_igc %>%
            group_by(
                gene, status,
                gene_chr, gene_start,
                gene_end, gene_length, gene_name, gene_id,
                pLI, exac_pLI,
                oe_lof_upper, pNull, oe_lof
            ) %>%
            dplyr::select(-score, -strand, -thickStart, -thickEnd, -color) %>%
            summarise(
                N_IGC = n(),
                support = sum(name, na.rm = T),
                average_support = support / N_IGC,
                average_length = mean(reference_end - reference_start),
            ) %>%
            ungroup() %>%
            pivot_wider(
                names_from = status,
                values_from = c(N_IGC, support, average_length, average_support),
                values_fill = 0
            ) %>%
            mutate(rank = support_Donor + support_Acceptor) %>%
            arrange(-rank) %>%
            dplyr::select(-support_Donor, -support_Acceptor)
    } else {

    }
    out_df$LOEUF <- out_df$oe_lof_upper
    out_df
}
gene_cols
igc_genes <- igc_in_genes(gene_bed)
head(igc_genes)
colnames(igc_genes)
igc_exons <- igc_in_genes(gene_bed6)
tables <- list(igc_genes, igc_exons)

wb <- createWorkbook()
## create and add a style to the column headers
headerStyle <- createStyle(
    fontSize = 11,
    fontColour = "#000000",
    borderColour = "#000000",
    halign = "center",
    border = "TopBottom",
)
## style for body
bodyStyle <- createStyle(borderStyle = "none", fontSize = 9, numFmt = "#,##0.00")
for (i in seq(length(tables))) {
    cur_tbl <- tables[[i]]
    rows <- seq(nrow(cur_tbl))
    cols <- seq(ncol(cur_tbl))
    print(i)
    print(cols)

    addWorksheet(
        wb = wb, sheetName = i,
        gridLines = FALSE
    )

    addStyle(wb, i, headerStyle, gridExpand = TRUE, cols = cols, rows = 1)
    addStyle(wb, i, bodyStyle, gridExpand = TRUE, cols = cols, rows = 2:(nrow(cur_tbl) + 1))
    freezePane(wb, sheet = i, firstCol = TRUE, firstRow = TRUE)
    setColWidths(wb, i, cols = cols, widths = "auto")
    writeData(wb = wb, sheet = i, x = cur_tbl)
}

saveWorkbook(wb, "tables/Gene_IGC.xlsx", overwrite = TRUE)

length(unique(igc_exons$gene_name))
```

```{r}
add_repel_pli <- function(p, pli = 0.5, nudge_x = -0.25,
                          nudge_y = 100, min_accpt = 0, min_donor = 0, y = 0, LOEUF = FALSE) {
    filter_df <- pli_plot.df %>%
        filter(
            pLI >= pli,
            N_IGC_Acceptor >= min_accpt,
            N_IGC_Donor >= min_donor
        )
    if (LOEUF) {
        filter_df <- pli_plot.df %>%
            filter(
                LOEUF <= 1,
                LOEUF >= 0,
                N_IGC_Acceptor >= min_accpt,
                N_IGC_Donor >= min_donor
            )
    }

    p + geom_text_repel(
        data = filter_df,
        aes_string(y = y),
        max.overlaps = 100,
        segment.alpha = 0.2,
        size = 3,
        force = 5,
        force_pull = 0.25,
        nudge_y = nudge_y,
        nudge_x = nudge_x
    ) +
        xlab("probability of being loss-of-function intolerant (pLI)") +
        theme_minimal_grid()
}

pli_plot.df <- igc_exons %>%
    group_by(gene_name, gene_id, pLI, exac_pLI, LOEUF, pNull) %>%
    replace(is.na(.), -0.1) %>%
    summarise(
        average_length_Donor = mean(average_length_Donor),
        average_length_Acceptor = mean(average_length_Acceptor),
        average_support_Donor = mean(average_support_Donor),
        average_support_Acceptor = mean(average_support_Acceptor),
        N_IGC_Donor = sum(N_IGC_Donor),
        N_IGC_Acceptor = sum(N_IGC_Acceptor)
    ) %>%
    data.table()

pli_plot.df[pLI >= 0.5]
sum(pli_plot.df$pLI < 0)
vals <- c("No data\navailable" = -0.1, `0.0` = 0.0, `0.25` = 0.25, `0.50` = 0.50, `0.75` = 0.75, `1.0` = 1.0)
var <- "LOEUF"
pli_plot_a <- (pli_plot.df %>%
    ggplot(aes(x = LOEUF, label = gene_name)) +
    geom_histogram(bins = 50) +
    ylab("Count of genes with IGC over exons")) %>%
    add_repel_pli(LOEUF = TRUE) +
    scale_x_continuous(breaks = vals)
ggsave("tmp.pdf")
library(ggpubr)
pli_plot_b <- (pli_plot.df %>%
    filter(pLI >= 0.0) %>%
    ggplot(aes(x = pLI, y = N_IGC_Acceptor, label = gene_name)) +
    geom_point()
# geom_smooth(method = "lm", se = F, alpha = 0.2, size = 1)
) %>%
    add_repel_pli(pli = 0.75, min_accpt = 50, y = "N_IGC_Acceptor") +
    ylab("# of IGC acceptor events")

pli_plot_c <- (pli_plot.df %>%
    filter(pLI >= 0.0) %>%
    ggplot(aes(x = pLI, y = N_IGC_Donor, label = gene_name)) +
    geom_point()
# stat_cor(method = "pearson") +
# geom_smooth(method = "lm", se = F, alpha = 0.2, size = 1)
) %>%
    add_repel_pli(pli = 0.5, min_donor = 50, y = "N_IGC_Donor") +
    ylab("# of IGC donor events")


pli_plot <- cowplot::plot_grid(
    pli_plot_a,
    cowplot::plot_grid(pli_plot_b, pli_plot_c),
    ncol = 1
) + theme(plot.background = element_rect(fill = "transparent", color = "transparent"))
s <- 0.75
ggsave("figures/igc_pli.pdf", plot = pli_plot, height = 12 * s, width = 20 * s)
ggsave("tmp.pdf", plot = pli_plot, height = 12 * s, width = 20 * s)



################################################################################## 33
# pli vs # of acceptor events

igc_exons %>%
    group_by(gene_id, gene_name, pLI) %>%
    summarise(N_IGC_Acceptor = sum(N_IGC_Acceptor)) %>%
    # filter(N_IGC_Acceptor > 0) %>%
    ggplot(aes(x = pLI, y = log10(N_IGC_Acceptor))) +
    geom_point() +
    geom_smooth(method = "lm") +
    stat_cor() +
    theme_minimal_grid()
ggsave("tmp.pdf")
```

## Donor vs acceptor across the genome, round 2

```{r}
igc_a.sd <- igc_sd[, c(acceptor_columns, "sample"), with = FALSE] %>%
    filter(`#reference_name.liftover` != "chrY") %>%
    data.table()
igc_d.sd <- igc_sd[, c(donor_columns, "sample"), with = FALSE] %>%
    filter(`reference_name` != "chrY") %>%
    data.table()
igc_cov_a.sd <- convert_to_sd_coords(igc_cov[name == "acceptor" & per >= 0.95], c(1, 2, 3), converter)
igc_cov_d.sd <- convert_to_sd_coords(igc_cov[name == "donor" & per >= 0.95], c(1, 2, 3), converter)

pt <- 3
pp <- getDefaultPlotParams(plot.type = pt) # $plot.params
pp$ideogramlateralmargin <- 0.01

g_size <- sum(converter$genome$end) / 1e6
count <- 0
n_bins <- 3
ii <- 0
sets <- list(c())
for (i in nrow(converter$genome)) {
    chr <- converter$genome$seqnames[i]
    end <- converter$genome$end[i]
    count <- count + end
    print(end)
    sets[[ii]] <- c(sets[[ii]], chr)
    if (count > g_size / 3) {
        count <- 0
        ii <- ii + 1
    }
}
sets
set1 <- NOYM[1:8]
set2 <- NOYM[8:length(NOYM)]

# pp$ideogramheight=100
pdf(glue("{odir}/ideo_gc_density.pdf"), height = 8, width = 30)
for (chrs in list(set1, set2)) {
    kp <- plotKaryotype(
        cytobands = converter$cyto,
        genome = converter$genome,
        # chromosomes = "chr1",
        chromosomes = chrs,
        plot.params = pp, plot.type = pt,
    )

    window <- 2e4
    d_bot <- 0.1
    kpPlotDensity(kp,
        data = toGRanges(igc_a.sd),
        r0 = d_bot, r1 = 1.0,
        data.panel = 1, window.size = window, col = acceptor_color
    ) # , border=acceptor_color)
    kpPlotDensity(kp,
        data = toGRanges(igc_d.sd),
        r0 = d_bot, r1 = 1.0,
        data.panel = 2, window.size = window, col = donor_color
    ) # , border=donor_color)

    kpPlotRegions(kp,
        data = toGRanges(GENES_V1.1.sd),
        r0 = -pp$data1inmargin / pp$data1height,
        r1 = 0, avoid.overlapping = FALSE,
        data.panel = 2,
        border = NA
    )

    kpPlotRegions(kp,
        data = (toGRanges(morb_sd[seqnames != "chrY#"])), #-width(toGRanges(morb_sd))/25,
        r1 = 0, r0 = -pp$data2inmargin / pp$data2height,
        data.panel = 1,
        col = transparent(morb_sd$color, 0.0), avoid.overlapping = TRUE, border = NA
    )

    kpPlotRegions(kp,
        data = GenomicRanges::reduce(toGRanges(igc_cov_a.sd)),
        data.panel = 1,
        # r0 = 0, r1 = d_bot,
        r0 = 0.9, r1 = 1.0,
        col = NEWCOLOR, border = NEWCOLOR
    )
    kpPlotRegions(kp,
        data = GenomicRanges::reduce(toGRanges(igc_cov_d.sd)),
        data.panel = 2,
        #   r0 = 0, r1 = d_bot,
        r0 = 0.9, r1 = 1.0,
        col = NEWCOLOR, border = NEWCOLOR
    )

    # kpAddCytobandLabels(kp, cex = .75)
    # kpPlotMarkers(kp, data=toGRanges(converter$cyto), labels=converter$cyto$name, text.orientation = "horizontal",
    #              r1=0.5, cex=0.8,adjust.label.position = FALSE)
}
dev.off()
dev.off()
dev.off()
dev.off()
```

```{r NEW IGC PLOT FOR GENES}
# @william, add genes here
igc_fig_genes <- c(
    "F8", "C4B", "HERC",
    "OPN1LW", "HBG1", "TCAF",
    "LPA", "CROCC", "NEB",
    "THOC3", "RPBD1", "RPUSD1", "GOLGA2",
    "RHD", "CYP2D6", "SRGAP2", "ARHGAP11",
    "TBC1D3[^[:digit:],P]", "NPIPA", "NPIPB",
    "HYDIN2",
    "SMN1", "SMN2"
)
igc_gene_pat <- paste0(paste0("(", paste(igc_fig_genes, collapse = "|")), ")")
igc_gene_pat
allowed_gene_types <- c(
    "protein_coding", "pseudogene",
    "processed_pseudogene", "processed_transcript"
)
pc_gene_bed <- gene_bed %>%
    filter(
        type %in% allowed_gene_types
    ) %>%
    data.table()


igc_with_genes <- merged_df %>%
    add_gene_list_col(
        genelist = pc_gene_bed,
        gene_cols = c(2, 3, 4),
        cols = acceptor_columns, outcol = "acceptor_genes",
        gene_name_col = "gene_name"
    ) %>%
    add_gene_list_col(
        genelist = pc_gene_bed,
        gene_cols = c(2, 3, 4),
        cols = donor_columns, outcol = "donor_genes",
        gene_name_col = "gene_name"
    )

igc_genes_of_interest <- merged_df %>%
    filter(
        grepl(igc_gene_pat, donor_gene_names) | grepl(igc_gene_pat, acceptor_gene_names)
    ) %>%
    mutate(gene_of_interest = str_extract(acceptor_gene_names, igc_gene_pat)) %>%
    mutate(gene_of_interest = case_when(
        is.na(gene_of_interest) ~ str_extract(donor_gene_names, igc_gene_pat),
        TRUE ~ gene_of_interest
    )) %>%
    mutate(gene_of_interest = gsub(";NA|NA;", "", gene_of_interest)) %>%
    mutate(gene_of_interest = gsub("TBC1D3.*", "TBC1D3", gene_of_interest))
igc_genes_of_interest

igc_genes_of_interest$gene_of_interest %>% unique()
igc_genes_of_interest$gene_of_interest %>%
    unique() %>%
    length()
length(igc_fig_genes)
```

```{r}
hap_cov <- fread("data/haplotype_coverage_bed_graph.bed")
colnames(hap_cov) <- c("chr", "start", "end", "coverage")

library(patchwork)
plot_layout <- "
AAAAAB
CCCCC#
"

regions_of_interest <- igc_genes_of_interest %>%
    dplyr::filter(reference_name == `#reference_name.liftover`) %>%
    group_by(reference_name, gene_of_interest) %>%
    summarise(
        chr = unique(reference_name),
        start = min(min(reference_start), min(reference_start.liftover)) - 1e4,
        end = max(max(reference_end), max(reference_end.liftover)) + 1e4,
        Mbp = (end - start) / 1e6,
        n = n()
    ) %>%
    dplyr::filter(!(gene_of_interest == "F8" & chr != "chrX")) %>%
    # filter(gene_of_interest == "SRGAP2C") %>%
    # filter(gene_of_interest == "OPN1LW") %>%
    data.table()
regions_of_interest
dim(regions_of_interest)


i <- 1
dt <- igc_genes_of_interest
min_snv <- 0
min_sample <- 0
n_events <- 1e6
for (i in 1:nrow(regions_of_interest)) {
    my_chrm <- regions_of_interest$chr[[i]]
    chrm <- regions_of_interest$chr[[i]]
    my_start <- regions_of_interest$start[[i]] - 5e3
    my_end <- regions_of_interest$end[[i]] + 5e3
    my_len <- my_end - my_start
    gene_of_interest <- regions_of_interest$gene_of_interest[[i]]
    my_gene_of_interest <- regions_of_interest$gene_of_interest[[i]]
    condition_name <- (
        dt$reference_name == dt$`#reference_name.liftover`
    ) & (dt$reference_name == my_chrm)
    condition1 <- condition_name &
        (dt$reference_start.liftover < my_end & dt$reference_end.liftover > my_start)
    condition2 <- condition_name &
        (dt$reference_start <= my_end & dt$reference_end >= my_start)


    cov_regions <- queryHits(findOverlaps(
        toGRanges(hap_cov),
        toGRanges(data.frame(chr = my_chrm, start = my_start, end = my_end))
    ))
    cur_cov <- hap_cov[cov_regions]

    cur_igc <-
        dt[condition1 & condition2] %>%
        filter(
            name >= min_snv,
            n >= min_sample,
        ) %>%
        as.tibble(.name_repair = "unique") %>%
        mutate(
            st1 = reference_start.liftover,
            st2 = reference_start,
            mid1 = (st1 + st2) / 2,
            en1 = reference_end.liftover,
            en2 = reference_end,
            mid2 = (en1 + en2) / 2,
            group = row_number()
        ) %>%
        arrange(st1 - en1, -n, -name) %>%
        mutate(y = disjointBins(IRanges(st1, en1)) / 10) %>%
        data.table()

    # my_start <- min(cur_igc$st1, cur_igc$st2)
    # my_end <- max(cur_igc$en2, cur_igc$en2)

    print(gene_of_interest)
    print(dim(cur_igc))
    cur_igc

    if (nrow(cur_igc) == 0) {
        next
    }

    head(gene_bed6$gene_id) %in% igc_genes$gene_id
    gene_ids_with_igc <- unique(unlist(
        strsplit(c(cur_igc$acceptor_gene_ids, cur_igc$donor_gene_ids), ";")
    ))

    df_genes <- gene_bed6 %>%
        filter(
            type %in% allowed_gene_types,
            chr == chrm,
            (start <= my_end & end >= my_start)
        ) %>%
        filter(!grepl("\\.", gene)) %>%
        filter(!grepl("^LINC", gene)) %>%
        # mutate(gene = sub("-\\d+", "", gene)) %>%
        group_by(gene_name, gene_id) %>%
        summarise(start = min(start) - 1e3, end = max(end) + 1e3) %>%
        mutate(gene = gene_name) %>%
        ungroup() %>%
        mutate(
            y = disjointBins(IRanges(start, end) + length / 5e3),
            color = (gene_id %in% gene_ids_with_igc) # grepl(gene_of_interest, gene)
        ) %>%
        arrange(color) %>%
        data.table()
    df_genes

    cur_morb <- morb %>%
        filter(
            seqnames == chrm,
            start <= my_end & end >= my_start
        ) %>%
        mutate(
            y = -disjointBins(IRanges(start, end)) / 3
        )

    p_genes <- ggplot(
        df_genes,
        aes(x = start, xend = end, y = y, yend = y)
    ) +
        geom_segment(aes(color = color),
            arrow = arrow(length = unit(0.1, "cm")),
            size = 0.75
        ) +
        geom_text_repel(
            data = df_genes %>% filter(color == TRUE),
            aes(label = gene, color = color),
            direction = "y",
            segment.size = .2,
            nudge_y = 1
        ) +
        geom_segment(
            data = cur_morb,
            aes(x = start, xend = end, y = y, yend = y),
            color = cur_morb$color,
        ) +
        scale_color_manual(values = c(`TRUE` = NEWCOLOR, `FALSE` = OLDCOLOR)) +
        coord_cartesian(
            clip = "off",
            xlim = c(my_start, my_end)
        ) +
        ylab("") +
        xlab("") +
        theme_minimal_vgrid() +
        theme(
            legend.position = "none",
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.line.y = element_blank(),
            plot.margin = margin(0, 0, .2, 0, "cm")
        )

    plot_cov <- ggplot(
        data = cur_cov,
        aes(
            x = pmax(start, my_start), xend = pmin(end, my_end),
            y = coverage, yend = coverage
        )
    ) +
        geom_segment() +
        coord_cartesian(
            clip = "off",
            # ylim = c(0, NA),
            xlim = c(my_start, my_end)
        ) +
        ylab("1:1 alignment\ncoverage") +
        xlab("") +
        theme_minimal_grid() +
        theme(
            legend.position = "none",
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank(),
            plot.margin = margin(0, 0, 0, 0, "cm")
        )
    # ggsave("tmp.pdf")

    cur_gc <- cur_igc %>%
        # arrange(-(st1 + en1) / 2) %>%
        arrange(n, -(st1 + en1) / 2) %>%
        mutate(id = paste(rev(row_number()), sample, sep = ": ")) %>%
        mutate(
            id = factor(id, levels = unique(id)),
            sample = factor(sample, levels = unique(sample))
        ) %>%
        mutate(arrow_st = case_when(st1 < st2 ~ st2, TRUE ~ en2)) %>%
        mutate(arrow_en = case_when(st1 < st2 ~ en1, TRUE ~ st1)) %>%
        data.table()
    cur_gc
    cur_igc
    curve <- 0.03
    p_gc <- cur_gc %>%
        ggplot(aes(y = id, yend = id)) +
        geom_segment(
            aes(x = st1, xend = en1, size = name, color = "Acceptor"),
            size = 3,
            alpha = 0.9, lineend = "round"
        ) +
        geom_segment(
            aes(
                x = st2,
                xend = en2,
                size = name,
                color = "Donor"
            ),
            size = 3,
            alpha = 0.9, lineend = "round"
        ) +
        geom_curve(aes(x = arrow_st, xend = arrow_en),
            arrow = arrow(angle = 15, length = unit(0.15, "inches")),
            curvature = curve, size = 0.25, color = NEWCOLOR
        ) +
        geom_text(aes(
            x = pmin((st1 + st1) / 2, (st2 + st2) / 2),
            label = round((en1 - st1) / 1e3, 1),
            color = "Length (kbp)",
        ),
        size = 3, nudge_y = 0, hjust = 1.5
        ) +
        geom_text(aes(
            x = pmax((en1 + en1) / 2, (en2 + en2) / 2),
            label = comma(name, accuracy = 0.1),
            color = "# SNVs",
        ),
        size = 3, nudge_y = 0, hjust = -0.5
        ) +
        scale_x_continuous("Genomic position",
            label = comma,
        ) +
        ylab("") +
        scale_color_manual("IGC",
            values = c(
                Acceptor = "darkblue",
                Donor = "darkorange",
                `Length (kbp)` = "#249D8C",
                `# SNVs` = NEWCOLOR
            )
        ) +
        scale_size_binned("# of supporting SNVs",
            range = c(0.1, 5),
            breaks = round(10**seq(0, 3, 0.3) / 10) * 10,
            nice.breaks = T,
        ) +
        guides(
            size = guide_legend(
                override.aes = list(color = "darkblue"),
                nrow = 2
            ),
            color = guide_legend(nrow = 1)
        ) +
        coord_cartesian(
            clip = "off",
            xlim = c(my_start, my_end)
        ) +
        # ggtitle(
        #   glue(
        #      "{n_events} largest IGC events in {min_sample} or more samples with at least {min_snv} SNVs"
        # ),
        # subtitle = glue(
        #   "{inv[[1]]}:{comma(inv[[2]])}-{comma(inv[[3]])}"
        # )
        # ) +
        theme_minimal_grid() +
        theme(
            strip.background = element_blank(),
            strip.text.x = element_blank(),
            panel.spacing.x = unit(0, "lines"),
            panel.spacing.y = unit(0, "lines"),
            legend.position = "top",
            legend.key.size = unit(1, "cm"),
            axis.text.y = element_text(size = 8),
            # plot.margin = margin(0, 0, 0, 0, unit = "pt")
        ) +
        ggtitle(glue("IGC in {gene_of_interest} on {chrm}"))

    p_hist <- cur_gc %>%
        ggplot(aes(y = id, x = n)) +
        geom_bar(stat = "identity") +
        theme_minimal_vgrid() +
        theme(
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank()
        ) +
        ylab("") +
        xlab("# of haplotypes\nwith IGC event") +
        theme(plot.margin = margin(0, 0, 0, 0, unit = "pt"))

    nrow_cur_gc <- nrow(cur_gc)

    print("saving")
    scale <- 1
    if (nrow_cur_gc <= 30) {
        scale <- 0.7
    }
    fig_height <- (max(11, nrow_cur_gc / 5 + 1)) * scale

    fig_patch <- p_gc + p_hist + p_genes + plot_spacer() + plot_cov +
        plot_layout(
            widths = c(5, 1),
            heights = c(fig_height - 2, 1, 1),
            nrow = 3, ncol = 2
        ) & theme(
        plot.background = element_rect(fill = "transparent", color = "transparent")
    )
    ggsave(glue("{odir}/genes/{gene_of_interest}_{chrm}_min_snv_{min_snv}_gc_fig.pdf"),
        limitsize = FALSE,
        # height=12,
        height = fig_height,
        width = 16 * scale,
        bg = "transparent",
        plot = fig_patch
    )
}

system(glue("pdfunite figures/genes/*min_snv_{min_snv}*.pdf figures/igc_all_genes_booklet_min_snv_{min_snv}.pdf"))
print("hi")
```

```{R}
system("module load miniconda/4.9.2  bcftools/1.12 && ~mvollger/assembly_breaks/asm-to-reference-alignment/workflow/scripts/add-missing-hom-genotypes.py data/gene-conversion/IGC.vcf /net/eichler/vol26/projects/assembly_breaks/nobackups/asm-to-reference-alignment/human_nhp_vcf_merge/all_hap_coverages.bed | bcftools sort | bgzip -@ 30 > data/gene-conversion/IGC.fixed.gt.vcf.gz")
system("module load miniconda/4.9.2  bcftools/1.12 && bcftools index data/gene-conversion/IGC.fixed.gt.vcf.gz")
```

# phil samples names

```{r}

high_pli_gene_for_phil <- pli_plot.df %>%
    filter(pLI >= 0.5) %>%
    merge(gene_bed, by = c("gene_id", "gene_name")) %>%
    group_by(gene_id, gene_name) %>%
    select(chr, start, end) %>%
    summarise(start = min(start), end = max(end))
validate_igc <- regions_of_interest[Mbp < 10, c("chr", "start", "end")] %>%
    bind_rows(igc_recur_df[, c("chrm", "st1", "en2")] %>%
        rename(chr = chrm, start = st1, end = en2), .id = "id")
validate_igc

colnames(gene_igc)
```

```{r}
keep_genes <- c("protein_coding", "transcribed_processed_pseudogene")
real_genes <- gene_bed[geneType %in% keep_genes & num_coding_exons > 1 & cds_length >= 200]
o <- findOverlaps(
    toGRanges(real_genes[, c("chr", "start", "end")]),
    toGRanges(merged_df[, ..donor_columns]),
    type = "within"
)
igc_full_gene <- bind_cols(merged_df[subjectHits(o)], real_genes[queryHits(o)]) # %>% head(1)
```

```{r}
wb <- createWorkbook()
moved_genes <- igc_full_gene %>%
    group_by(gene_name, gene_id, pLI, cds_length, num_coding_exons, geneType) %>%
    summarise(
        igc_events_non_redudant = length(unique(paste(group, reference_name)))
        # igc_events_non_redudant = n(),
        # igc_events = sum(igc_count)
    ) %>%
    arrange(-igc_events_non_redudant)

addWorksheet(wb = wb, sheetName = "Moved genes", gridLines = FALSE)
writeData(wb = wb, sheet = "Moved genes", x = moved_genes)

colnames(igc_full_gene)
group_cols <- c(
    "group",
    "#reference_name.liftover", "reference_start.liftover", "reference_end.liftover",
    "name...7", "reference_name", "reference_start", "reference_end", "Sample", "sample", "n"
)

igc_events_that_move_full_genes <- igc_full_gene %>%
    group_by_at(vars(one_of(group_cols))) %>%
    summarise(
        gene = paste(unique(gene), collapse = ";"),
        geneid = paste(unique(gene_id), collapse = ";"),
        pLI = paste(unique(pLI), collapse = ";"),
        cds_length = paste(unique(cds_length), collapse = ";")
    ) %>%
    dplyr::rename(
        `Ave supporting SNVs` = `name...7`
    ) %>%
    ungroup() %>%
    mutate(
        length = reference_end - reference_start,
        # dist_between = pmin(
        #    abs(reference_start - reference_start.liftover),
        #    abs(reference_end - reference_end.liftover),
        #    abs(reference_end - reference_start.liftover),
        #    abs(reference_start - reference_end.liftover)
        # ),
        dist_between = my_min_dist(
            reference_start, reference_end,
            reference_start.liftover, reference_end.liftover
        )
    ) %>%
    dplyr::select(-sample, -n) %>%
    data.table()

addWorksheet(wb = wb, sheetName = "IGC events that move genes", gridLines = FALSE)
writeData(wb = wb, sheet = "IGC events that move genes", x = igc_events_that_move_full_genes)

saveWorkbook(wb, "tables/igc_moves_full_gene.xlsx", overwrite = TRUE)
```

```{r}

my_min_dist <- function(st1, en1, st2, en2) {
    # print(head(st2-en1))
    # print(head(st1-en2))
    cond1 <- st2 > en1
    rtn <- st2 - en1
    cond2 <- en1 >= st2
    rtn[cond2] <- st1[cond2] - en2[cond2]
    print(sum(cond1, cond2))
    print(data.table(st1, en1, st2, en2, cond1, cond2, rtn))
    rtn
}

igc_events_that_move_full_genes %>%
    filter(`#reference_name.liftover` == reference_name) %>%
    summarise(
        `Ave. supporting SNVs` = mean(`Ave supporting SNVs`),
        `Med supporting SNVs` = median(`Ave supporting SNVs`),
        `Ave length` = mean(length),
        `Med length` = median(length),
        dist_between_mean = mean(dist_between),
        dist_between_median = median(dist_between)
    )
```

```{r}
igc_events_that_move_full_genes %>%
    filter(`#reference_name.liftover` == reference_name) %>%
    ggplot(
        aes(x = dist_between, y = length)
    ) +
    geom_point() +
    stat_cor(method = "pearson") +
    geom_smooth(method = "lm", color = "darkred", se = FALSE, linetype = "dashed") +
    scale_y_continuous("IGC length", trans = "log10", label = comma) +
    scale_x_continuous("Distance between IGC acceptor and donor", trans = "log10", label = comma) +
    theme_minimal_grid()

igc_events_that_move_full_genes %>%
    filter(`#reference_name.liftover` == reference_name) %>%
    ggplot(
        aes(y = reference_name, yend = reference_name)
    ) +
    geom_segment(
        aes(x = reference_start, xend = reference_end),
        color = acceptor_color, fill = acceptor_color,
        size = 3, alpha = 0.75
    ) +
    geom_segment(
        aes(x = reference_start.liftover, xend = reference_end.liftover),
        color = donor_color, fill = donor_color,
        size = 3, alpha = 0.75
    ) +
    geom_curve(
        aes(x = reference_start.liftover, xend = reference_end),
        color = "darkred", size = 0.1, # , linetype="dashed"
        curvature = 0.2
    ) +
    facet_grid2(reference_name ~ ., scales = "free", independent = "x", axes = "all") +
    # facet_col2(free="x")+
    scale_x_continuous("", label = comma) +
    coord_cartesian(clip = "off") +
    theme_minimal_grid()
ggsave("tmp.pdf", height = 20)
```

```{r}
# add in callable regions
# all_covs <- fread(cmd = "zcat *bed.gz")
data_path <- "data/alignments/callable/"
files <- dir(data_path, pattern = "*.bed.gz")
files
t_data <- tibble(filename = files) %>%
    mutate(file_contents = map(
        filename,
        ~ read_table(file.path(data_path, .), col_names = F)
    )) %>%
    unnest(file_contents)
colnames(t_data)[2:length(t_data)] <- c("chr", "start", "end", "ct", "ct.st", "ct.en")
cov_by_hap <- t_data %>%
    # separate(ct, into = c("sample", "hap", "ct_name"), sep = "#", remove = F) %>%
    separate(
        filename,
        into = c("sample", "hap", "z", "x"), sep = "_", remove = F
    ) %>%
    mutate(
        Sample = paste(sample, hap, sep = "_"),
    ) %>%
    filter(Sample != "CHM1_2") %>%
    filter(Sample != "GRCh38_2") %>%
    data.table()
cov_by_hap
```

```{r}
# example data

regions_of_interest_2 <- igc_full_gene[,
    as.data.table(IRanges::reduce(IRanges(
        pmin(reference_start, reference_start.liftover) - 1e0,
        pmax(reference_end, reference_end.liftover) + 1e0,
    ))),
    by = .(reference_name)
] %>% dplyr::mutate(
    chr = `reference_name`
)
nrow(regions_of_interest_2)


# system("mkdir -p figures/igc_moves_full_gene")

for (i in 1:nrow(regions_of_interest_2)) {
    row <- regions_of_interest[i, ]
    # print(row$reference_name)
    my_start <- row$start
    my_end <- row$end
    cur_df <- igc_full_gene %>%
        filter(
            `#reference_name.liftover` == row$reference_name &
                ((reference_end >= row$start & reference_start <= row$end) |
                    (reference_end.liftover >= row$start & reference_start.liftover <= row$end))
        )
    cur_hap_cov <- cov_by_hap %>%
        filter(
            chr == row$reference_name &
                ((end >= my_start & start <= my_end))
        ) %>%
        # group_by(Sample) %>%
        mutate(
            bin = disjointBins(IRanges(start, end))
        ) %>%
        ungroup()

    if (nrow(cur_df) == 0) {
        next
    }

    cur_igc <- cur_df %>%
        group_by_at(vars(one_of(group_cols))) %>%
        summarise(n_genes = n()) %>%
        mutate(
            st1 = reference_start.liftover,
            st2 = reference_start,
            mid1 = (st1 + st2) / 2,
            en1 = reference_end.liftover,
            en2 = reference_end,
            mid2 = (en1 + en2) / 2,
            group = row_number()
        ) %>%
        ungroup() %>%
        mutate(y = disjointBins(IRanges(st1, en1))) %>%
        arrange(n, -(st1 + en1) / 2) %>%
        mutate(id = paste(rev(row_number()), sample, sep = ": ")) %>%
        mutate(
            id = factor(id, levels = unique(id)),
            sample = factor(sample, levels = unique(sample)),
            name = `name...7`,
        ) %>%
        mutate(arrow_st = case_when(st1 < st2 ~ st2, TRUE ~ en2)) %>%
        mutate(arrow_en = case_when(st1 < st2 ~ en1, TRUE ~ st1)) %>%
        data.table()

    df_genes <- cur_df %>%
        group_by(gene_name, gene_id, geneName) %>%
        # summarise(start = min(start) - 1e3, end = max(end) + 1e3) %>%
        mutate(
            gene = gene_name,
            transcript_num = row_number(),
        ) %>%
        ungroup() %>%
        mutate(
            y = disjointBins(IRanges(start, end) + length / 5e3),
        ) %>%
        data.table()


    plot_genes <- ggplot(
        df_genes,
        aes(x = start, xend = end, y = y, yend = y)
    ) +
        geom_segment(
            arrow = arrow(length = unit(0.1, "cm")),
            size = 0.75
        ) +
        geom_text_repel(
            data = . %>% filter(transcript_num == 1),
            aes(label = gene),
            # direction = "x",
            segment.size = .2,
            min.segment.length = 0,
            nudge_y = -max(max(df_genes$y) / 3, 2)
        ) +
        coord_cartesian(
            clip = "off",
            xlim = c(my_start, my_end)
        ) +
        ylab("") +
        xlab("") +
        theme_minimal_vgrid() +
        theme(
            legend.position = "none",
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.line.y = element_blank(),
            plot.margin = margin(0, 0, .2, 0, "cm")
        )

    plot_cov <- ggplot(
        data = cur_hap_cov,
        aes(
            x = pmax(start, my_start), xend = pmin(end, my_end),
            y = paste(Sample, bin), yend = paste(Sample, bin)
        )
    ) +
        geom_segment(size = 3) +
        coord_cartesian(
            clip = "off",
            # ylim = c(0, NA),
            xlim = c(my_start, my_end)
        ) +
        ylab("1:1 assembly\ncoverage") +
        xlab("") +
        theme_minimal_grid() +
        # facet_nested(Sample ~ ., scales = "free_y", switch = "both") +
        theme(
            legend.position = "none",
            axis.ticks.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.y = element_blank(),
            axis.text.y = element_blank(),
            # panel.spacing = unit(0, "lines"),
            plot.margin = margin(0, 0, 0, 0, "cm")
        )
    # ggsave("tmp.pdf")

    plot_igc <- cur_igc %>%
        ggplot(aes(y = id, yend = id)) +
        geom_segment(
            aes(x = st1, xend = en1, size = name, color = "Acceptor"),
            size = 3,
            alpha = 0.9, lineend = "round"
        ) +
        geom_segment(
            aes(
                x = st2,
                xend = en2,
                size = name,
                color = "Donor"
            ),
            size = 3,
            alpha = 0.9, lineend = "round"
        ) +
        geom_curve(aes(x = arrow_st, xend = arrow_en),
            arrow = arrow(angle = 15, length = unit(0.15, "inches")),
            curvature = curve, size = 0.25, color = NEWCOLOR
        ) +
        geom_text(aes(
            x = pmin((st1 + st1) / 2, (st2 + st2) / 2),
            label = round((en1 - st1) / 1e3, 1),
            color = "Length (kbp)",
        ),
        size = 3, nudge_y = 0, hjust = 1.5
        ) +
        geom_text(aes(
            x = pmax((en1 + en1) / 2, (en2 + en2) / 2),
            label = comma(name, accuracy = 0.1),
            color = "# SNVs",
        ),
        size = 3, nudge_y = 0, hjust = -0.5
        ) +
        scale_x_continuous(glue("{row$reference_name} position"),
            label = comma,
        ) +
        ylab("") +
        scale_color_manual("IGC",
            values = c(
                Acceptor = "darkblue",
                Donor = "darkorange",
                `Length (kbp)` = "#249D8C",
                `# SNVs` = NEWCOLOR
            )
        ) +
        scale_size_binned("# of supporting SNVs",
            range = c(0.1, 5),
            breaks = round(10**seq(0, 3, 0.3) / 10) * 10,
            nice.breaks = T,
        ) +
        guides(
            size = guide_legend(
                override.aes = list(color = "darkblue"),
                nrow = 2
            ),
            color = guide_legend(nrow = 1)
        ) +
        coord_cartesian(
            clip = "off",
            xlim = c(my_start, my_end)
        ) +
        theme_minimal_grid() +
        theme(
            strip.background = element_blank(),
            strip.text.x = element_blank(),
            panel.spacing.x = unit(0, "lines"),
            panel.spacing.y = unit(0, "lines"),
            legend.position = "bottom",
            legend.key.size = unit(1, "cm"),
            axis.text.y = element_text(size = 8),
        )

    plot_hist <- cur_igc %>%
        ggplot(aes(y = id, x = n)) +
        geom_bar(stat = "identity") +
        theme_minimal_vgrid() +
        theme(
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank()
        ) +
        ylab("") +
        xlab("# of haplotypes\nwith IGC event") +
        theme(plot.margin = margin(0, 0, 0, 0, unit = "pt"))

    fig_patch <-
        plot_genes + plot_spacer() +
            # plot_cov + plot_spacer() +
            plot_igc + plot_hist +
            plot_layout(
                widths = c(5, 1),
                heights = c(1, 5),
                nrow = 2, ncol = 2
            ) & theme(
            plot.background = element_rect(
                fill = "transparent", color = "transparent"
            )
        )

    ggsave(
        glue("figures/igc_moves_full_gene/{i}_move.pdf"),
        height = nrow(cur_igc) / 2 + 3, width = 10
    )
    if (i > 3) {
        break
    }
}

system("pdfunite figures/igc_moves_full_gene/*_move.pdf figures/igc_moves_full_gene.pdf")
```



```{r}
sd_space <- 120e6
u_space <- 2500e6
sd_vars <- sd_space * 15 / 1e4
u_vars <- u_space * 9 / 1e4
m <- matrix(c(sd_vars, u_vars, sd_space, u_space), nrow = 2)
# m = matrix(c(sd_vars, sd_space, u_vars, u_space), nrow=2)
m
chisq.test(m)
```



```{r}
large_igc <- merged_df %>%
    filter(length >= quantile(length, 0.9)) # %>% head(300)
min(large_igc$length)

pdf("figures/large_igc_events_top_10_percent.pdf")
kp <- plotKaryotype(
    plot.type = 1, cytobands = CYTOFULL, genome = GENOME, chromosomes = NOYM
)
kpPlotLinks(
    kp,
    data = toGRanges(large_igc[, ..acceptor_columns]),
    data2 = toGRanges(large_igc[, ..donor_columns]),
    col = NEWCOLOR,
    # border = NA
    border = transparent(NEWCOLOR, 0.9)
)
kpAddCytobands(kp)
dev.off()
```

