
```{r}
# library(ruler)
library(tidyverse)
library(data.table)
library(latex2exp)
library(ggfortify)
library(compositions)
library(conflicted)
library(stringr)
library(glue)
library(ggrepel)
library(cowplot, help, pos = 2, lib.loc = NULL)
library(ggforce, help, pos = 2, lib.loc = NULL)
library(ggh4x)
conflicted::conflict_prefer(name = "select", winner = "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("ungroup", "dplyr")
conflict_prefer("summarise", "dplyr")
conflict_prefer("pivot_wider", "tidyr")
```

```{r}
source("load-data.R")
```
```{r}
IS_IGC <- "-no-igc"

SD_var <- "SDnoIGC"
SD_var <- "SDIGC"
SD_var <- "SD"

population <- ""
population <- "_population"

unique_targets <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/Unique_targets.txt"))
u_cov <- fread("data/mutyper-results-no-igc/hap_covs/Unique.bed", col.names = c("chr", "st", "en", "cov")) %>% summarise(sum(cov * (en - st)) / sum(en - st))
u_cov <- u_cov[[1]]



# for saving results
wb <- createWorkbook()

for (population in c("")) { # , "_population"
    for (SD_var in c("SD", "SDnoIGC", "SDIGC")) { #
        # get hap coverage for SDs
        sd_cov <- fread(glue("data/mutyper-results-no-igc/hap_covs/{SD_var}.bed"), col.names = c("chr", "st", "en", "cov")) %>% summarise(sum(cov * (en - st)) / sum(en - st))
        sd_cov <- sd_cov[[1]]
        adj_ratio <- sd_cov / u_cov
        adj_ratio
        # normalize for missing haplotypes in SDs

        sd_targets <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/{SD_var}_targets.txt"))
        targets <- bind_rows(
            list(SD = sd_targets, Unique = unique_targets),
            .id = "stratify"
        )
        colnames(targets)[2:3] <- c("first_three_bases", "target_count")
        spectra <- fread(glue("data/mutyper-results{IS_IGC}/tables/stratify/spectra_{SD_var}_Unique{population}.tbl")) %>%
            mutate(
                stratify = case_when(
                    stratify == SD_var ~ "SD",
                    TRUE ~ stratify
                ),
                change_to = substr(spectra, 6, 6),
                change = paste(mid_base, ">", change_to)
            ) %>%
            merge(targets, by = c("first_three_bases", "stratify")) %>%
            # normalize counts so same # of counts happen in SD and unique
            group_by(stratify) %>%
            mutate(
                # norm = sum(count)/sum(target_count),
                # count = count / sum(count),
                # target_count = target_count / sum(target_count)
            ) %>%
            ungroup() %>%
            as.data.table()
        if (population == "") {
            is_sd <- spectra$stratify == "SD"
            spectra$count[is_sd] <- spectra$count[is_sd] / adj_ratio
        }

        print(spectra %>% group_by(stratify) %>% summarise(sum(count) / 1e6, sum(target_count) / 1e6, sum(count) / sum(target_count), z = SD_var, y = population))

        grouped_spectra <- spectra %>%
            group_by(
                stratify, mid_base,
                spectra, first_base, last_base,
                first_three_bases, first_two_bases,
                change, change_to,
                target_count
            ) %>%
            summarise(count = sum(count), n_samples = length(unique(sample))) %>%
            mutate(
                count_adj = count / target_count,
                target_percent = count / target_count,
                spectra = gsub(">.", ">", spectra),
                spectra = gsub(".$", "", spectra),
            ) %>%
            ungroup() %>%
            group_by(stratify) %>%
            mutate(
                target_rate = target_percent,
                target_percent = target_percent / sum(target_percent)
            ) %>%
            as.data.table()
        grouped_spectra

        k <- grouped_spectra %>%
            group_by(stratify) %>%
            summarise(sum(count), sum(target_count), sum(target_percent))
        print(k)

        spectra_table <- grouped_spectra %>%
            mutate(
                # y = count_aj,
                y = target_percent,
            ) %>%
            pivot_wider(
                names_from = c("stratify"), values_from = c("y", "target_rate"),
                id_cols = c("spectra", "first_base", "mid_base", "first_three_bases", "last_base", "change", "change_to"),
            ) %>%
            mutate(
                SD = y_SD,
                Unique = y_Unique,
                # y = log2(SD / Unique),
                y = SD / Unique,
                size = abs(SD - Unique),
                z_rank = rank(y),
                per = z_rank / max(z_rank),
                `# GC bases` = as.character(str_count(first_three_bases, "G|C"))
            ) %>%
            arrange(
                `# GC bases`,
                y,
                mid_base,
                spectra,
            ) %>%
            mutate(
                spectra = factor(spectra, levels = spectra)
            ) %>%
            as.data.table()
        spectra_table

        spectra_plot <- spectra_table %>%
            data.table() %>%
            ggplot(
                aes(
                    x = spectra,
                    # x=last_base,
                    # x=first_base,
                    y = y, label = spectra,
                    color = `# GC bases`,
                )
            ) + # , color = stratify)) +
            theme_minimal_grid() +
            geom_point(size = 3) +
            # geom_text(aes(label=last_base))+
            geom_text_repel(
                data = . %>% filter(per <= 0.15 | per >= 0.85),
                # nudge_y = .05, # )/10,
                # nudge_x = -1,
                force = 20,
                box.padding = 0.5,
                min.segment.length = 0,
                # direction = "y",
                color = "black",
                size = 3,
            ) +
            scale_x_discrete(guide = guide_axis(n.dodge = 6)) +
            # facet_nested(.~  change + last_base, scales = "free_x", switch="x")+
            scale_color_viridis_d(direction = -1) +
            scale_fill_viridis_d(direction = -1) +
            # triplet-normalized mutation frequency
            ylab(TeX("$ \\frac{SD \\; triplet-normalized \\; mutation \\; frequency}{Unique \\; triplet-normalized \\; mutation \\; frequency}$")) +
            xlab("Mutation event") +
            # ylim(0.5,1.5) +
            theme(
                legend.position = "top",
                panel.spacing = unit(1.2, "pt"),
                strip.background = element_rect(color = "black"),
                plot.margin = margin(0.1, 1, 0.1, 0.1, unit = "cm"),
            ) +
            coord_cartesian(clip = "off")
        spectra_plot
        # ggsave(glue("figures/seq_comp{IS_IGC}.pdf"), width = 12)
        # ggsave("tmp.pdf", width = 12)



        # sum(fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/{SD_var}_spectra.txt"))[, 2:97]) / 1e6
        # sum(fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/Unique_spectra.txt"))[, 2:97]) / 1e6

        color_end <- round(max(abs(log2(spectra_table$y))) + 0.05, 1)

        spectra_plot <- spectra_table %>%
            mutate(
                color = cut(log2(y), breaks = seq(-color_end, color_end, 0.2)),
                first_three_bases = factor(first_three_bases, levels = sort(unique(first_three_bases)))
            ) %>%
            data.table() %>%
            ggplot(
                aes(
                    # y = first_three_bases,
                    # x = change_to,
                    fill = log2(y),
                    y = first_base,
                    x = last_base,
                    # y = y, label = spectra,
                    # color = `# GC bases`,
                )
            ) + # , color = stratify)) +
            theme_minimal_grid() +
            geom_tile(color = "black") +
            facet_nested(. ~ change, scales = "free_x", switch = "both") +
            xlab("3' base") +
            ylab("5' base") +
            # scale_color_viridis_c() +
            # scale_fill_viridis_c() +
            scale_fill_steps2(
                "log2FC",
                high = "darkred", mid = "white", low = "darkblue",
                midpoint = 0,
                n.breaks = 11,
                limits = c(-color_end, color_end)
            ) +
            # scale_fill_brewer("log2 fold change", palette = "Spectral", direction=-1, drop=FALSE)+
            # scale_color_brewer("Fold change", palette = "Spectral")+
            theme_minimal_grid() +
            theme(
                legend.key.height = unit(1, "cm"), # change legend key height
                legend.key.width = unit(5, "cm"), # change legend key width
                legend.position = "top",
            )
        # ggsave("tmp.pdf", width=12)


        ########################################################################################
        ########################################################################################
        ########################################################################################

        target_diffs <- targets %>%
            pivot_wider(
                names_from = c("stratify"), values_from = "target_count",
                id_cols = c("first_three_bases"),
            ) %>%
            mutate(
                total_sd = sum(SD),
                total_u = sum(Unique),
                fold = (SD / total_sd) / (Unique / total_u),
                log2 = log2(fold)
            ) %>%
            rowwise() %>%
            mutate(
                matrix = list(
                    matrix(c(SD, Unique, total_sd - SD, total_u - Unique), nrow = 2)
                ),
                # stat_test = list(chisq.test(c(SD, Unique), c(total_sd, total_u))),
                # stat_test = fisher.test(matrix)$p.value,
                stat_test = list(chisq.test(matrix)), # $p.value,
                pval = stat_test$p.value * nrow(.),
                `# GC bases` = as.character(str_count(first_three_bases, "G|C"))
            ) %>%
            ungroup() %>%
            arrange(
                `# GC bases`,
                log2,
                first_three_bases
            ) %>%
            mutate(
                first_three_bases = factor(first_three_bases, levels = first_three_bases)
            )
        target_diffs

        target_plot <- ggplot(
            target_diffs,
            aes(
                x = first_three_bases,
                # y = log2,
                y = fold,
                # y = -log10(pval),
                # color = pval < 0.05,
                label = first_three_bases,
                color = `# GC bases`,
            )
        ) +
            geom_point(size = 3) +
            scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
            scale_color_viridis_d(direction = -1) +
            ylab(TeX("$ \\frac{SD \\; composition}{Unique \\; composition}$")) +
            xlab("") +
            theme_minimal_grid() +
            theme(legend.position = "top")

        ########################################################################################
        ########################################################################################
        ########################################################################################



        spectra_wide <- spectra %>%
            mutate(target_percent = count / target_count) %>%
            group_by(stratify) %>%
            mutate(target_percent = target_percent / sum(target_percent)) %>%
            ungroup() %>%
            merge(pop_small, by.x = "sample", by.y = "SampleID", all.x = TRUE) %>%
            # filter(stratify == "Unique") %>%
            pivot_wider(id_cols = c("stratify", "sample", "Superpopulation"), names_from = c("spectra"), values_from = c("target_percent")) %>%
            data.table()
        spec_mat <- spectra_wide[, 4:ncol(spectra_wide)]
        spec_mat %>% as.tibble()
        # normatize per row
        spec_mat <- t(apply(spec_mat, 1, function(x) (x) / (sum(x))))
        # log scale per will suggestion
        spec_mat <- clr(spec_mat)

        spectra_pca <- prcomp(spec_mat) # , scale. = TRUE)
        sort(spectra_pca$rotation[, 1])

        pca_plot <- autoplot(spectra_pca,
            data = spectra_wide,
            colour = "Superpopulation",
            shape = "stratify",
            # x = 4, y = 5
        ) +
            scale_color_brewer("", palette = "Set1") +
            scale_shape_discrete("") +
            guides(
                color = guide_legend(nrow = 2),
                shape = guide_legend(nrow = 2)
            ) +
            theme_minimal_grid() +
            theme(
                legend.position = "top"
            )
        pca_plot
        # ggsave("tmp.pdf")

        ########################################################################################
        ########################################################################################
        ########################################################################################
        mutable_triplets.df <- spectra %>%
            group_by(stratify, first_three_bases, target_count) %>%
            summarise(count = sum(count)) %>%
            # filter(stratify=="Unique") %>%
            group_by(stratify) %>%
            mutate(
                triplet_frac = target_count / sum(target_count),
                # target_count = sum(target_count),
                mutable = count / target_count
            ) %>%
            arrange(-mutable) %>%
            pivot_wider(
                names_from = c("stratify"), values_from = c("mutable", "triplet_frac", "target_count", "count"),
                id_cols = c("first_three_bases"),
            ) %>%
            mutate(
                x = mutable_Unique,
                # y = log2(triplet_frac_SD/triplet_frac_Unique),
                y = triplet_frac_SD / triplet_frac_Unique,
                label = paste(first_three_bases, round(y, 2)),
                CpG = substr(first_three_bases, 2, 3) == "CG"
            )

        mutable_triplets_text <- mutable_triplets.df %>%
            summarise(
                pred_SD_variants = sum(count_SD),
                pred_SD_variants = sum(mutable_Unique * target_count_SD),
                SD_targets = sum(target_count_SD),
                Unique_variants = sum(count_Unique),
                Unique_targets = sum(target_count_Unique),
                pred_SD_rate = pred_SD_variants / SD_targets,
                SD_rate = sum(count_SD) / SD_targets,
                Unique_rate = Unique_variants / Unique_targets,
                expected_increase = round(100 * (pred_SD_rate / Unique_rate - 1), 2)
            )
        print(mutable_triplets_text)

        mutable_triplets <- mutable_triplets.df %>%
            filter(!CpG) %>%
            ggplot(aes(x = x, y = y, label = label)) +
            geom_text_repel(min.segment.length = 0) +
            geom_smooth(method = "lm", se = F, formula = y ~ x) +
            geom_point() +
            stat_cor(method = "pearson") +
            # stat_regline_equation(label.y = 30) +
            ggtitle("",
                subtitle = glue(
                    "{mutable_triplets_text$expected_increase}% expected increase in SD mutations due to triplet context"
                )
            ) +
            scale_x_continuous(
                "Frequency of mutation in unique sequence",
                trans = "log10"
            ) +
            annotation_logticks(side = "b") +
            ylab(TeX("$ \\; \\frac{SD \\; composition}{Unique  \\; composition}$")) +
            theme_minimal_grid()
        # ggsave("tmp.pdf", plot=mutable_triplets)
        mutable_triplets
        mutable_triplets.df
        ########################################################################################
        ########################################################################################
        ########################################################################################

        layout <- "
        AAAAABBBBB
        CCCCCBBBBB
        DDDDDDDDDD
        DDDDDDDDDD
        "
        library(patchwork)
        # fig <- plot.timing + target_plot + pca_plot + spectra_plot + # plot.timing +
        fig <- target_plot + mutable_triplets + pca_plot + spectra_plot + # plot.timing +
            plot_layout(design = layout) +
            plot_annotation(tag_levels = "a") & theme(plot.tag = element_text(size = 24))
        scale <- 0.8
        # ggsave("tmp.pdf", fig, width = 16 * scale, height = 16 * scale)
        ggsave(glue("figures/full-figs/mutyper{population}_{SD_var}.pdf"), fig, width = 16 * scale, height = 16 * scale)
        ggsave(glue("tmp.pdf"), fig, width = 16 * scale, height = 16 * scale)

        ########################################################################################
        ########################################################################################
        ########################################################################################

        # save data
        sheet <- spectra_table %>%
            arrange(-y) %>%
            mutate(`Fold change` = SD / Unique) %>%
            select(spectra, `Fold change`, SD, Unique)
        ws_name <- glue("{SD_var}{population}")
        addWorksheet(wb = wb, sheetName = ws_name, gridLines = FALSE)
        writeData(wb = wb, sheet = ws_name, x = sheet)

        grep_term <- "(A|T).>(C|G)"
        get_enrichment <- function(spectra_table, grep_term, norm = TRUE) {
            if (norm) {
                z <- spectra_table %>%
                    arrange(-y) %>%
                    mutate(`Fold change` = SD / Unique)
            } else {
                z <- spectra_table %>%
                    arrange(-y) %>%
                    mutate(`Fold change` = target_rate_SD / target_rate_Unique)
            }
            z <- z %>%
                select(spectra, `Fold change`, SD, Unique) %>%
                filter(grepl(grep_term, spectra)) %>%
                summarise(
                    change = sum(SD) / sum(Unique),
                )
            round(z[[1]], 3)
        }

        groups <- data.table(
            change = c(
                ".(A|T).>(C|G)",
                ".(C|G).>(A|T)",
                ".CG>T",
                ".C.>A",
                ".C.>G",
                ".C.>T",
                ".A.>C",
                ".A.>G",
                ".A.>T",
                "...>A",
                "...>T",
                "...>C",
                "...>G"
            )
        ) %>%
            group_by(change) %>%
            mutate(
                `Fold change` = get_enrichment(spectra_table, change),
                `Fold change (not normalized for counts)` = get_enrichment(spectra_table, change, norm = FALSE),
                # change = gsub("\\.", "N", change)
            )
        groups
        ws_name <- glue("{SD_var}{population}_groups")
        print(ws_name)
        addWorksheet(wb = wb, sheetName = ws_name, gridLines = FALSE)
        writeData(wb = wb, sheet = ws_name, x = groups)


        # ggsave("tmp.pdf")
    }
}

# saveWorkbook(wb, "tables/Triplet_fold_increases.xlsx", overwrite = TRUE)
```



# some stats from the figs
```{r}

spectra_table <- data.table(spectra_table)
spectra_table[grepl(".CG>T", spectra), ] %>%
    mutate(ave = 1 - SD / Unique) %>%
    summarise(mean(ave), 1 - mean(SD / Unique), 1 - sum(SD) / sum(Unique))

targets %>%
    mutate(mid_base = substr(first_three_bases, 2, 2)) %>%
    group_by(stratify) %>%
    mutate(total = sum(target_count)) %>%
    group_by(mid_base, stratify) %>%
    summarise(
        frac = sum(target_count) / total,
        total
    ) %>%
    unique()
t.test(
    x = c(rep(1, 122193647 * 0.424), rep(0, 122193647 * (1 - .424))),
    # y=c(rep(1, 2542623043/1e4*.408), rep(0, 2542623043/1e4*(1-.408) )  ),
    mu = 0.408,
    alternative = "greater"
)
```



```{r}

t.p <- grouped_spectra %>%
    group_by(stratify) %>%
    mutate(norm_target_percent = target_percent / sum(target_percent) * 100) %>%
    ungroup() %>%
    pivot_wider(id_cols = c("spectra", "first_three_bases"), names_from = stratify, values_from = norm_target_percent) %>%
    mutate(`# GC bases` = as.character(str_count(first_three_bases, "G|C"))) %>%
    arrange(-Unique) %>%
    mutate(spectra = factor(spectra, levels = unique(spectra)))

ggsave("tmp.pdf")


t.p.p <- t.p %>%
    ggplot(aes(color = `# GC bases`, y = Unique, x = spectra)) +
    geom_point() +
    facet_col(~`# GC bases`)


ggsave("tmp.pdf")
```


# unused chunks ?
```{r }
seq_con.df <- fread(glue("data/mutyper-results{IS_IGC}/spectra/stratify/seq_content.tbl"))
colnames(seq_con.df)[length(seq_con.df)] <- "stratify"

seq_summary <- seq_con.df %>%
    filter(stratify %in% c("SD", "Unique")) %>%
    group_by(stratify) %>%
    summarise(
        A = sum(`6_num_A`),
        C = sum(`7_num_C`),
        G = sum(`8_num_G`),
        T = sum(`9_num_T`)
    ) %>%
    group_by(stratify) %>%
    mutate(
        Total = (sum(A) / 1e3 + sum(T) / 1e3 + sum(G) / 1e3 + sum(C) / 1e3) * 1e3,
        GC = (sum(G) + sum(C)) / Total,
        AT = (sum(A) + sum(T)) / Total
    )

z <- spectra %>%
    group_by(
        stratify, mid_base,
        spectra, first_base, last_base,
        first_three_bases, first_two_bases,
        target_count
    ) %>%
    summarise(count = sum(count)) %>%
    merge(seq_summary)

```


```{r}
```


```{r}
fread("data/mutyper-results-no-igc/spectra/stratify/Unique_spectra.txt") %>%
    select(-sample) %>%
    sum() / 1e9
fread("data/mutyper-results-no-igc/spectra/stratify/SD_spectra.txt") %>%
    select(-sample) %>%
    sum() / 1e9
fread("data/mutyper-results-no-igc/spectra/spectra.txt") %>%
    select(-sample) %>%
    sum() / 1e9
# [1] 1.195006
```


# transitions vs transversions 
```{r}
data <- "count ref       alt
 844801 A       C
3039573 A       G
 690172 A       T
 851018 C       A
1003546 C       G
3097834 C       T
3039966 G       A
1021253 G       C
 876990 G       T
 694095 T       A
3051903 T       C
 871036 T       G"

sd_ts_tv <- fread(data)

data <- "count ref       alt
10389503 A      C
41930445 A      G
9027918 A       T
10502321 C      A
10828922 C      G
41922995 C      T
41893989 G      A
10851334 G      C
10442272 G      T
9055724 T       A
41906837 T      C
10463409 T      G"

u_ts_tv <- fread(data)

transitions <- c("AG", "GA", "CT", "TC")

ts_tv <- bind_rows(
    list(SD = sd_ts_tv, Unique = u_ts_tv),
    .id = "stratify"
) %>% mutate(
    z = paste(ref, alt, sep = "")
)
ts_tv$type <- "Transversion"
ts_tv$type[ts_tv$z %in% transitions] <- "Transition"

ts_tv
```

```{r}
ts_tv_ratio <- ts_tv %>%
    group_by(type, stratify) %>%
    summarise(
        frac = sum(count)
    ) %>%
    pivot_wider(
        id_cols = c("stratify", "type"),
        names_from = c("type"),
        values_from = c("frac")
    ) %>%
    mutate(`ts/tv` = Transition / Transversion) %>%
    data.table()

chisq.test(
    matrix(unlist(ts_tv_ratio[, c("Transition", "Transversion")]), nrow = 2, ncol = 2)
)
ts_tv_ratio
```

# allele frequencies
```{r}
maf_counts <- HPRC_SNVS %>%
    # sample_n(1e6) %>%
    filter(anno_SD == TRUE | anno_Unique == TRUE) %>%
    group_by(anno_SD, ID) %>%
    summarise(
        allele_count = n()
    ) %>%
    group_by(allele_count, anno_SD) %>%
    summarise(
        frac = n()
    )
```

```{r}

z <- maf_counts %>%
    mutate(
        type = case_when(anno_SD == TRUE ~ "SD", TRUE ~ "Unique"),
        allele_count = case_when(
            allele_count <= 50 ~ allele_count,
            TRUE ~ as.integer(101) - allele_count
        ),
        # allele_count = cut(allele_count ,
        #    breaks = seq(1, 51, 2), include.lowest = TRUE
        # )
    ) %>%
    group_by(type, allele_count) %>%
    summarise(frac = sum(frac)) %>%
    group_by(type) %>%
    mutate(frac = frac / sum(frac)) %>%
    ggplot(aes(x = allele_count, y = frac, fill = type)) +
    # geom_histogram(bins = seq(1,51,2), stat = "identity") +
    geom_bar(stat = "identity", position = "dodge") +
    # facet_col(. ~ type, scales = "free_y") +
    scale_y_continuous("Density", label = comma) +
    scale_x_continuous("Allele frequency") +
    scale_fill_manual("", values = c(NEWCOLOR, OLDCOLOR)) +
    theme_minimal_grid() +
    theme(legend.position = "top")
ggsave("tmp.pdf")
```


```{r}
colnames(snv_counts) <- c(
    "chr", "start", "end", "id",
    "anno_SD", "anno_Unique", "count",
    "x", "y", "z", "coverage"
)
snv_counts <- snv_counts[anno_SD | anno_Unique]
snv_counts <- snv_counts[coverage <= 102 & coverage >= 80]

snv_counts %>%
    group_by(anno_SD) %>%
    summarise(n() / 1e6)
```


```{r}
snv_counts %>%
    # head(1e6) %>%
    mutate(
        type = case_when(anno_SD == TRUE ~ "SD", TRUE ~ "Unique"),
        count = case_when(
            count > 102 ~ 51.0,
            count > 51 ~ 102.0 - count,
            TRUE ~ 1.0 * count
        ),
        af = pmin(count / coverage, 1),
        af = case_when(
            af > 0.5 ~ 1 - af,
            TRUE ~ af
        )
    ) %>%
    ggplot(aes(x = af, fill = type, group = type)) +
    geom_histogram(
        # aes(y = stat(count / sum(count))),
        aes(y = ..density.. / 100),
        position = "dodge", breaks = seq(1 / 102, 0.55, 2 / 102)
    ) +
    # facet_col(~type, scales = "free_y") +
    scale_y_continuous("Density") +
    scale_x_continuous("Allele frequency", limits = c(1 / 102, 0.5)) +
    scale_fill_manual("", values = c(NEWCOLOR, OLDCOLOR)) +
    theme_minimal_grid() +
    theme(legend.position = "top")
ggsave("tmp.pdf")
```


